### ISSUE TITLE
onGameStart fails silently to user

### ISSUE THREAD

**Issue by sky1113** [empiricaly/empirica#126]
If a stage is not configured correctly, it throws an error to the server console, such as the one below.

```bash
empirica_1   | [callbacks] Error: stage: addStage requires duration option
empirica_1   | [callbacks]     at addStage (/app/server/node_modules/@empirica/admin/dist-src/store.js:359:19)
empirica_1   | [callbacks]     at Context.<anonymous> (file:///app/server/src/callbacks.mjs:39:9)
empirica_1   | [callbacks]     at emitFull (/app/server/node_modules/@empirica/admin/dist-src/runtime.js:59:17)
empirica_1   | [callbacks]     at emit (/app/server/node_modules/@empirica/admin/dist-src/runtime.js:44:20)
empirica_1   | [callbacks]     at processChange (/app/server/node_modules/@empirica/admin/dist-src/runtime.js:571:36)
empirica_1   | [callbacks]     at Runtime.processChanges (/app/server/node_modules/@empirica/admin/dist-src/runtime.js:441:24)
empirica_1   | [callbacks]     at processTicksAndRejections (node:internal/process/task_queues:96:5)
empirica_1   | [callbacks]     at EventEmitter.emitFull (/app/server/node_modules/@empirica/admin/dist-src/runtime.js:60:17)
empirica_1   | [callbacks]     at Runtime.handleAttribute (/app/server/node_modules/@empirica/admin/dist-src/runtime.js:655:9)
empirica_1   | [callbacks]     at Runtime.processEventLocked (/app/server/node_modules/@empirica/admin/dist-src/runtime.js:429:21)
```
The game fails to start but the user is left on game loading screen. Instead, they should see some error message or that no games are available.

@JamesPHoughton

**Comment by npaton** [comment]
This comes down to bad handling of callback errors, which we track in #135. I will close this ticket, check for #135 for updates on this.
