### ISSUE TITLE
[Bug] Empirica v2 fails to start again after completing a game and shutting down server

### ISSUE THREAD

**Issue by stevenrick** [empiricaly/empirica#159]
## Expected Behavior

Empirica should start.

## Current Behavior

Fails to start when run a second time after a game is completed during first run. The `empirica` command errors out. 

```
[server] building file list ... 
[server] 0 files to consider
[server] 
[server] sent 29 bytes  received 20 bytes  98.00 bytes/sec
[server] total size is 0  speedup is 0.00
[client] 
[client]   vite v2.9.15 dev server running at:
[client] 
[client]   > Local:    http://localhost:8844/
[client]   > Network:  http://192.168.50.252:8844/
[client] 
[client]   ready in 361ms.
[client] 
[server] 
[server]   dist/index.js      432.9kb
[server]   dist/index.js.map    1.5mb
[server] 
[server] ⚡ Done in 66ms
error when starting dev server:
Error: Port 8844 is already in use
    at Server.onError (/Users/srick/dev/test/client/node_modules/vite/dist/node/chunks/dep-689425f3.js:48206:28)
    at Server.emit (node:events:513:28)
    at emitErrorNT (node:net:1459:8)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
21:29:39.420 ERR player: command failed, restarting error="exit status 1" waiting=735.127272ms
[server] [UnhandledPromiseRejection: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason "[object Object]".] {
[server]   code: 'ERR_UNHANDLED_REJECTION'
[server] }
[server] building file list ... 
[server] 0 files to consider
[server] 
[server] sent 29 bytes  received 20 bytes  98.00 bytes/sec
[server] total size is 0  speedup is 0.00
[server] 
[server]   dist/index.js      432.9kb
[server]   dist/index.js.map    1.5mb
[server] 
[server] ⚡ Done in 68ms
POTENTIAL DEADLOCK:
Previous place where the lock was grabbed
goroutine 81 lock 0x14000521890
/go/pkg/mod/github.com/empiricaly/tajriba@v1.0.0-rc.11/internal/runtime/scope.go:308 runtime.(*Runtime).SubScopedAttributes.func1 ??? <<<<<
/go/pkg/mod/github.com/empiricaly/tajriba@v1.0.0-rc.11/internal/runtime/scope.go:307 runtime.(*Runtime).SubScopedAttributes.func1 ???

Have been trying to lock it again for more than 3s
goroutine 98 lock 0x14000521890
/go/pkg/mod/github.com/empiricaly/tajriba@v1.0.0-rc.11/internal/runtime/hooks.go:172 runtime.(*Runtime).SubOnEvent.func1 ??? <<<<<
/go/pkg/mod/github.com/empiricaly/tajriba@v1.0.0-rc.11/internal/runtime/hooks.go:171 runtime.(*Runtime).SubOnEvent.func1 ???

Here is what goroutine 81 doing now
goroutine 81 [semacquire]:
sync.runtime_SemacquireMutex(0x100010032?, 0x78?, 0xc108?)
	/usr/local/go/src/runtime/sema.go:71 +0x28
sync.(*Mutex).lockSlow(0x1400020baec)
	/usr/local/go/src/sync/mutex.go:162 +0x180
sync.(*Mutex).Lock(0x14000703860?)
	/usr/local/go/src/sync/mutex.go:81 +0x84
github.com/sasha-s/go-deadlock.lock(0x14000813ee0, {0x1057f5420?, 0x1400020baec})
	/go/pkg/mod/github.com/sasha-s/go-deadlock@v0.3.1/deadlock.go:230 +0x188
github.com/sasha-s/go-deadlock.(*Mutex).Lock(...)
	/go/pkg/mod/github.com/sasha-s/go-deadlock@v0.3.1/deadlock.go:85
github.com/empiricaly/tajriba/internal/runtime.(*Runtime).SubScopedAttributes.func1()
	/go/pkg/mod/github.com/empiricaly/tajriba@v1.0.0-rc.11/internal/runtime/scope.go:311 +0x4f0
created by github.com/empiricaly/tajriba/internal/runtime.(*Runtime).SubScopedAttributes
	/go/pkg/mod/github.com/empiricaly/tajriba@v1.0.0-rc.11/internal/runtime/scope.go:262 +0x360
Other goroutines holding locks:
goroutine 260 lock 0x1400020baec
/go/pkg/mod/github.com/empiricaly/tajriba@v1.0.0-rc.11/internal/runtime/scope.go:381 runtime.(*Runtime).pushAttributesForScopedAttributes.func1 ??? <<<<<
/go/pkg/mod/github.com/empiricaly/tajriba@v1.0.0-rc.11/internal/runtime/scope.go:380 runtime.(*Runtime).pushAttributesForScopedAttributes.func1 ???
```

## Possible Solution

The issue might be due to a failure to correctly handle SIGINT and terminate all processes cleanly leading to something holding onto and blocking ports. This issue only seems to arise after games are run and data is written to database. This does not happen if you create the experiment but never run any games. Further error noted when deleting the `test` directory with `rm -rf test`

```
node:events:491
      throw er; // Unhandled 'error' event
      ^

Error: write EPIPE
    at afterWriteDispatched (node:internal/stream_base_commons:160:15)
    at writeGeneric (node:internal/stream_base_commons:151:3)
    at Socket._writeGeneric (node:net:874:11)
    at Socket._write (node:net:886:8)
    at writeOrBuffer (node:internal/streams/writable:391:12)
    at _write (node:internal/streams/writable:332:10)
    at Socket.Writable.write (node:internal/streams/writable:336:10)
    at console.value (node:internal/console/constructor:299:16)
    at console.log (node:internal/console/constructor:376:26)
    at output (/Users/srick/dev/test/client/node_modules/vite/dist/node/chunks/dep-689425f3.js:18936:32)
Emitted 'error' event on Socket instance at:
    at emitErrorNT (node:internal/streams/destroy:157:8)
    at emitErrorCloseNT (node:internal/streams/destroy:122:3)
    at processTicksAndRejections (node:internal/process/task_queues:83:21) {
  errno: -32,
  code: 'EPIPE',
  syscall: 'write'
}
```

## Steps to Reproduce (for bugs)

1. in terminal run `empirica create test` then `cd test` and finally start with `empirica`
2. in admin interface, create one new batch with a 'complete' assignment method and one 'solo' treatment, and finally start the batch
3. in participant interface, complete the task until 'finished' screen
4. stop empirica running in the terminal with `ctrl+c` (sigint)
5. try to start empirica again by running `empirica` and you will see the error

## Context
Exploring the built-in example to start learning empirica

## Your Environment
- Version used: v2 latest darwin/arm64
- Operating System and version: OS X 12.6 desktop, M1 MBP

**Comment by stevenrick** [comment]
No modifications, just a clean new project using the `create` command

**Comment by npaton** [comment]
This should be fixed.
