### ISSUE TITLE
export command failing to load

### ISSUE THREAD

**Issue by npaton** [empiricaly/empirica#177]
```
root@abe4fe47d3ae:/build# empirica export
Setting up export environment...
19:49:13.886 INF exporting data args="npm run export -- --filename /build/deliberation-2022-11-02-19-49-13.zip --tajfile /build/.empirica/local/tajriba.json --srtoken HErChTCtHqDuhziZ"

> export@1.0.0 export
> npm run build && node --trace-warnings --enable-source-maps dist/index.js


> export@1.0.0 build
> esbuild src/index.js --platform=node --define:process.env.NODE_ENV='"production"' --bundle --minify --outfile=dist/index.js --sourcemap

✘ [ERROR] No matching export in "node_modules/@empirica/core/dist/admin-classic.js" for import "ExportFormat"

    src/index.js:2:2:
      2 │   ExportFormat,
        ╵   ~~~~~~~~~~~~

✘ [ERROR] No matching export in "node_modules/@empirica/core/dist/admin-classic.js" for import "runExport"

    src/index.js:3:2:
      3 │   runExport,
        ╵   ~~~~~~~~~

✘ [ERROR] No matching export in "node_modules/@empirica/core/dist/admin-classic.js" for import "withTajriba"

    src/index.js:4:2:
      4 │   withTajriba,
        ╵   ~~~~~~~~~~~

3 errors
19:49:24.453 FTL empirica: failed to start error="npm run export -- --filename /build/deliberation-2022-11-02-19-49-13.zip --tajfile /build/.empirica/local/tajriba.json --srtoken HErChTCtHqDuhziZ: exit status 1"
19:49:24.465 FTL empirica: failed to start error="run export script: exit status 1" 
```

**Comment by npaton** [comment]
What version are you running (`empirica version`)?

**Comment by npaton** [comment]
I think this is due to using an older version. That said, there is a problem in a later release, so I wouldn't upgrade just yet. Next release coming soon.

**Comment by npaton** [comment]
In the latest release, the other problem is fixed, so you can upgrade (`empirica upgrade`).

**Comment by JamesPHoughton** [comment]
Export is running well on my dev container, but running into issues on the server. Not quite sure what directory to be running the command from, so I tried the obvious candidates:
```bash
root@deliberation-empirica-5dc8c848d9-xhw22:/# empirica export
Setting up export environment...
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0xb4a74d]

goroutine 1 [running]:
github.com/empiricaly/empirica/cmds/empirica/cmd.addExportCommand.func1(0xc0001e3400, {0x1353ab8, 0x0, 0x0?})
        /build/cmds/empirica/cmd/export.go:62 +0x36d
github.com/spf13/cobra.(*Command).execute(0xc0001e3400, {0x1353ab8, 0x0, 0x0})
        /go/pkg/mod/github.com/spf13/cobra@v1.5.0/command.go:872 +0x694
github.com/spf13/cobra.(*Command).ExecuteC(0xc000103180)
        /go/pkg/mod/github.com/spf13/cobra@v1.5.0/command.go:990 +0x3b4
github.com/spf13/cobra.(*Command).Execute(...)
        /go/pkg/mod/github.com/spf13/cobra@v1.5.0/command.go:918
github.com/empiricaly/empirica/cmds/empirica/cmd.Execute()
        /build/cmds/empirica/cmd/root.go:139 +0x1e5
main.main()
        /build/cmds/empirica/main.go:8 +0x17


root@deliberation-empirica-5dc8c848d9-xhw22:/# cd app
root@deliberation-empirica-5dc8c848d9-xhw22:/app# empirica export
15:48:56.948 FTL invalid config error="validate tajriba configuration: validate auth configuration: please add at least one user in the configuration"

root@deliberation-empirica-5dc8c848d9-xhw22:/app# cd /.empirica/
root@deliberation-empirica-5dc8c848d9-xhw22:/.empirica# empirica export
15:49:17.243 FTL invalid config error="validate tajriba configuration: validate auth configuration: please add at least one user in the configuration"
```
