### ISSUE TITLE
Error on Custom Assignment

### ISSUE THREAD

**Issue by JamesPHoughton** [empiricaly/empirica#184]
I'm working through learning how to do customAssignment, and running into this error. Not sure if its because I'm not entering something that the custom assignment wants to see, or if its a bug. 

```
empirica_1  | [server] 17:31:07.149 ERR Error caught in "batch" callback:
empirica_1  | [server] 17:31:07.640 ERR ZodError: [
empirica_1  | [server] 17:31:07.642 ERR   {
empirica_1  | [server] 17:31:07.643 ERR     "code": "invalid_union_discriminator",
empirica_1  | [server] 17:31:07.645 ERR     "options": [
empirica_1  | [server] 17:31:07.645 ERR       "simple",
empirica_1  | [server] 17:31:07.646 ERR       "complete"
empirica_1  | [server] 17:31:07.646 ERR     ],
empirica_1  | [server] 17:31:07.646 ERR     "path": [
empirica_1  | [server] 17:31:07.646 ERR       "kind"
empirica_1  | [server] 17:31:07.646 ERR     ],
empirica_1  | [server] 17:31:07.646 ERR     "message": "Invalid discriminator value. Expected 'simple' | 'complete'"
empirica_1  | [server] 17:31:07.646 ERR   }
empirica_1  | [server] 17:31:07.649 ERR ]
empirica_1  | [server] 17:31:07.649 ERR /build/server/node_modules/zod/lib/index.mjs:449
empirica_1  | [server] 17:31:07.649 ERR const error = new ZodError(ctx.common.issues);
empirica_1  | [server] 17:31:07.649 ERR ^
empirica_1  | [server] 17:31:07.649 ERR ZodError: [
empirica_1  | [server] 17:31:07.650 ERR {
empirica_1  | [server] 17:31:07.650 ERR "code": "invalid_union_discriminator",
empirica_1  | [server] 17:31:07.650 ERR "options": [
empirica_1  | [server] 17:31:07.650 ERR "simple",
empirica_1  | [server] 17:31:07.650 ERR "complete"
empirica_1  | [server] 17:31:07.650 ERR ],
empirica_1  | [server] 17:31:07.650 ERR "path": [
empirica_1  | [server] 17:31:07.650 ERR "kind"
empirica_1  | [server] 17:31:07.650 ERR ],
empirica_1  | [server] 17:31:07.651 ERR "message": "Invalid discriminator value. Expected 'simple' | 'complete'"
empirica_1  | [server] 17:31:07.651 ERR }
empirica_1  | [server] 17:31:07.651 ERR ]
empirica_1  | [server] 17:31:07.651 ERR   at gN (/build/server/node_modules/zod/lib/index.mjs:449:23)
empirica_1  | [server] 17:31:07.652 ERR   at Rs.safeParse (/build/server/node_modules/zod/lib/index.mjs:561:16)
empirica_1  | [server] 17:31:07.652 ERR   at Rs.parse (/build/server/node_modules/zod/lib/index.mjs:541:29)
empirica_1  | [server] 17:31:07.652 ERR   at Object.callback (/build/server/node_modules/@empirica/core/src/admin/classic/classic.ts:239:40)
empirica_1  | [server] 17:31:07.652 ERR   at <anonymous> (/build/server/node_modules/@empirica/core/src/admin/cake.ts:229:30)
empirica_1  | [server] 17:31:07.652 ERR   at h (/build/server/node_modules/rxjs/src/internal/operators/mergeInternals.ts:71:15)
empirica_1  | [server] 17:31:07.652 ERR   at p (/build/server/node_modules/rxjs/src/internal/operators/mergeInternals.ts:53:58)
empirica_1  | [server] 17:31:07.653 ERR   at t.u._next (/build/server/node_modules/rxjs/src/internal/operators/OperatorSubscriber.ts:70:13)
empirica_1  | [server] 17:31:07.653 ERR   at t.t.next (/build/server/node_modules/rxjs/src/internal/Subscriber.ts:75:12)
empirica_1  | [server] 17:31:07.653 ERR   at <anonymous> (/build/server/node_modules/rxjs/src/internal/Subject.ts:68:20)
empirica_1  | [server] Batch ID 01GHVK3PZPYNDRHQ5Q2J00AY0B
empirica_1  | [server] 17:35:00.159 ERR Error caught in "batch" callback:
empirica_1  | [server] 17:35:00.674 ERR ZodError: [
empirica_1  | [server] 17:35:00.676 ERR   {
empirica_1  | [server] 17:35:00.677 ERR     "code": "invalid_union_discriminator",
empirica_1  | [server] 17:35:00.677 ERR     "options": [
empirica_1  | [server] 17:35:00.677 ERR       "simple",
empirica_1  | [server] 17:35:00.677 ERR       "complete"
empirica_1  | [server] 17:35:00.677 ERR     ],
empirica_1  | [server] 17:35:00.678 ERR     "path": [
empirica_1  | [server] 17:35:00.678 ERR       "kind"
empirica_1  | [server] 17:35:00.678 ERR     ],
empirica_1  | [server] 17:35:00.678 ERR     "message": "Invalid discriminator value. Expected 'simple' | 'complete'"
empirica_1  | [server] 17:35:00.678 ERR   }
empirica_1  | [server] 17:35:00.678 ERR ]
empirica_1  | [server] 17:35:00.678 ERR /build/server/node_modules/zod/lib/index.mjs:449
empirica_1  | [server] 17:35:00.678 ERR const error = new ZodError(ctx.common.issues);
empirica_1  | [server] 17:35:00.678 ERR ^
empirica_1  | [server] 17:35:00.678 ERR ZodError: [
empirica_1  | [server] 17:35:00.678 ERR {
empirica_1  | [server] 17:35:00.678 ERR "code": "invalid_union_discriminator",
empirica_1  | [server] 17:35:00.679 ERR "options": [
empirica_1  | [server] 17:35:00.679 ERR "simple",
empirica_1  | [server] 17:35:00.679 ERR "complete"
empirica_1  | [server] 17:35:00.679 ERR ],
empirica_1  | [server] 17:35:00.679 ERR "path": [
empirica_1  | [server] 17:35:00.679 ERR "kind"
empirica_1  | [server] 17:35:00.679 ERR ],
empirica_1  | [server] 17:35:00.679 ERR "message": "Invalid discriminator value. Expected 'simple' | 'complete'"
empirica_1  | [server] 17:35:00.679 ERR }
empirica_1  | [server] 17:35:00.679 ERR ]
empirica_1  | [server] 17:35:00.679 ERR   at gN (/build/server/node_modules/zod/lib/index.mjs:449:23)
empirica_1  | [server] 17:35:00.680 ERR   at Rs.safeParse (/build/server/node_modules/zod/lib/index.mjs:561:16)
empirica_1  | [server] 17:35:00.680 ERR   at Rs.parse (/build/server/node_modules/zod/lib/index.mjs:541:29)
empirica_1  | [server] 17:35:00.680 ERR   at Object.callback (/build/server/node_modules/@empirica/core/src/admin/classic/classic.ts:239:40)
empirica_1  | [server] 17:35:00.680 ERR   at <anonymous> (/build/server/node_modules/@empirica/core/src/admin/cake.ts:229:30)
empirica_1  | [server] 17:35:00.680 ERR   at h (/build/server/node_modules/rxjs/src/internal/operators/mergeInternals.ts:71:15)
empirica_1  | [server] 17:35:00.680 ERR   at p (/build/server/node_modules/rxjs/src/internal/operators/mergeInternals.ts:53:58)
empirica_1  | [server] 17:35:00.681 ERR   at t.u._next (/build/server/node_modules/rxjs/src/internal/operators/OperatorSubscriber.ts:70:13)
empirica_1  | [server] 17:35:00.681 ERR   at t.t.next (/build/server/node_modules/rxjs/src/internal/Subscriber.ts:75:12)
empirica_1  | [server] 17:35:00.681 ERR   at <anonymous> (/build/server/node_modules/rxjs/src/internal/Subject.ts:68:20)
```

## Env:
ghcr.io/empiricaly/empirica:build-154
"@empirica/core": "1.0.0-rc.23",

**Comment by npaton** [comment]
To use custom assignment, you need to disable some of the normal behavior on the backend.

[On this line in your project](https://github.com/empiricaly/empirica/blob/main/internal/templates/source/callbacks/src/index.js#L27) (under `server/src/index.js`), you need to pass 1 or more options. The primary one is `disableGameCreation`.

```js
  ctx.register(Classic({ disableGameCreation: true }));
```

It turns out, this option is no longer useful if you create a batch with the custom assignment. This is what you seem to have done and why you were getting the error. In the next update, this is fixed. Creating a batch with a "custom" assignment strategy will have the same effect as `disableGameCreation`. Either will work.

Then there are 2 more options you can (and probably want to) pass to Classic on the server:
```js
  // Disables automatic assignment of players on the connection of a new player.
  // It is up to the developer to call `game.assignPlayer` when they want to
  // assign a player to a game.
  disableAssignment?: boolean;

  // Disable the introDone check (when the players are done with intro steps),
  // which normally will check if enough players are ready (done with intro
  // steps) to start a game. This means that the game will not start on its own
  // after intro steps. It is up to the developer to start the game manually
  // with `game.start()`.
  // This also disables playerCount checks and overflow from one game to the
  // next available game with the same treatment.
  disableIntroCheck?: boolean;
```

On the client side, you also need to disable some default behavior. You will do this on `<EmpiricaContext>`, found in `client/src/App.jsx`. Here's a quick example:

```jsx
          <EmpiricaContext unmanagedAssignment disableNoGames>
            <Game />
          </EmpiricaContext>
```

And here are the relevant options you can pass to EmpiricaContext:

```js
  // An unmanaged game will render the children as soon as the Game is available
  // whether the round or stage are available or not. It is up to the developer
  // to handle the presence of the round and stage.
  // Everything else is still managed: the consent, the player, the intro
  // steps, the lobby, and the game.
  // This is not recommended for most games.
  // This is useful for games that want to persist render state between rounds
  // or stages. E.g. keep a video chat up between stages.
  unmanagedGame: boolean;

  // Unmanaged assignement will render the children as soon as the player is
  // connected. It is up to the developer to handle everything after the player
  // is connected: intro steps, lobby, game, round, stage and exit steps.
  unmanagedAssignment: boolean;

  // Disable the consent screen. It is up to the developer to handle the consent
  // screen.
  disableConsent: boolean;

  // Disable the NoGames screen. It is up to the developer to handle the NoGames
  // condition.
  disableNoGames: boolean;
```

We will need to create full documentation about custom assignments. There are many possible strategies. In essence, you want to disable parts of the standard behavior and add your own logic.
