### ISSUE TITLE
Error caught in "stage.ended" callback: "Input not instance of L0"

### ISSUE THREAD

**Issue by JamesPHoughton** [empiricaly/empirica#265]
Had the following error in dev environment today, I think I've had the same issue in prod:

```bash
deliberation-empirica-empirica-1  | [server] Batch  01GV1RV0464TW6RV1BBSW82JJ8 launched
deliberation-empirica-empirica-1  | [server] 23:30:16.495 ERR Error caught in "stage.ended" callback:
deliberation-empirica-empirica-1  | [server] 23:30:16.905 ERR ZodError: [
deliberation-empirica-empirica-1  | [server] 23:30:16.906 ERR   {
deliberation-empirica-empirica-1  | [server] 23:30:16.906 ERR     "code": "custom",
deliberation-empirica-empirica-1  | [server] 23:30:16.907 ERR     "message": "Input not instance of L0",
deliberation-empirica-empirica-1  | [server] 23:30:16.908 ERR     "fatal": true,
deliberation-empirica-empirica-1  | [server] 23:30:16.909 ERR     "path": []
deliberation-empirica-empirica-1  | [server] 23:30:16.909 ERR   }
deliberation-empirica-empirica-1  | [server] 23:30:16.909 ERR ]
deliberation-empirica-empirica-1  | [server] 23:30:16.909 ERR /build/server/node_modules/zod/lib/index.mjs:449
deliberation-empirica-empirica-1  | [server] 23:30:16.909 ERR const error = new ZodError(ctx.common.issues);
deliberation-empirica-empirica-1  | [server] 23:30:16.909 ERR ^
deliberation-empirica-empirica-1  | [server] 23:30:16.911 ERR ZodError: [
deliberation-empirica-empirica-1  | [server] 23:30:16.911 ERR {
deliberation-empirica-empirica-1  | [server] 23:30:16.911 ERR "code": "custom",
deliberation-empirica-empirica-1  | [server] 23:30:16.911 ERR "message": "Input not instance of L0",
deliberation-empirica-empirica-1  | [server] 23:30:16.911 ERR "fatal": true,
deliberation-empirica-empirica-1  | [server] 23:30:16.912 ERR "path": []
deliberation-empirica-empirica-1  | [server] 23:30:16.912 ERR }
deliberation-empirica-empirica-1  | [server] 23:30:16.912 ERR ]
deliberation-empirica-empirica-1  | [server] 23:30:16.912 ERR   at g1 (/build/server/node_modules/zod/lib/index.mjs:449:23)
deliberation-empirica-empirica-1  | [server] 23:30:16.912 ERR   at Fn.safeParse (/build/server/node_modules/zod/lib/index.mjs:561:16)
deliberation-empirica-empirica-1  | [server] 23:30:16.912 ERR   at Fn.parse (/build/server/node_modules/zod/lib/index.mjs:541:29)
deliberation-empirica-empirica-1  | [server] 23:30:16.912 ERR   at <anonymous> (/build/server/node_modules/@empirica/core/src/admin/classic/classic.ts:641:22)
deliberation-empirica-empirica-1  | [server] 23:30:16.912 ERR   at Object.callback (/build/server/node_modules/@empirica/core/src/admin/events.ts:88:11)
deliberation-empirica-empirica-1  | [server] 23:30:16.912 ERR   at Object.next (/build/server/node_modules/@empirica/core/src/admin/cake.ts:309:30)
deliberation-empirica-empirica-1  | [server] 23:30:16.913 ERR   at e.e.next (/build/server/node_modules/rxjs/src/internal/Subscriber.ts:161:25)
deliberation-empirica-empirica-1  | [server] 23:30:16.913 ERR   at t.t._next (/build/server/node_modules/rxjs/src/internal/Subscriber.ts:119:22)
deliberation-empirica-empirica-1  | [server] 23:30:16.913 ERR   at t.t.next (/build/server/node_modules/rxjs/src/internal/Subscriber.ts:75:12)
deliberation-empirica-empirica-1  | [server] 23:30:16.913 ERR   at <anonymous> (/build/server/node_modules/rxjs/src/internal/Subject.ts:68:20)
deliberation-empirica-empirica-1  | [server] game is now starting with players: 01GV1RVB90YEJGN48JAAY4T9Y1,01GV1RVAFZ520VQF778JS151PB
deliberation-empirica-empirica-1  | [server] [UnhandledPromiseRejection: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason "[object Object]".] {
deliberation-empirica-empirica-1  | [server]   code: 'ERR_UNHANDLED_REJECTION'
deliberation-empirica-empirica-1  | [server] }
```
Maybe related to: https://en.wikipedia.org/wiki/General_Zod?

According to the logs, this is coming before the game actually starts, so I don't know why there is an error in the `stage.ended` callback. I don't have a custom end of stage callback, so I guess this is internal to empirica core?

I saw this while running e2e tests, so it's possible that its left over from a previous test, and not actually properly ordered after the batch launch...

I'm also not sure if this is just one error, as I'm also getting the `UnhandledPromiseRejection` error in other places without the Zod error.

# Env:
FROM ghcr.io/empiricaly/empirica:build-249
"@empirica/core": "1.0.6",

**Comment by JamesPHoughton** [comment]
Also seeing in a few other places:
```bash
deliberation-empirica-empirica-1  | [server] 23:48:53.705 ERR Error caught in "round.start" callback:
deliberation-empirica-empirica-1  | [server] 23:48:54.152 ERR ZodError: [
deliberation-empirica-empirica-1  | [server] 23:48:54.152 ERR   {
deliberation-empirica-empirica-1  | [server] 23:48:54.153 ERR     "code": "invalid_type",
deliberation-empirica-empirica-1  | [server] 23:48:54.153 ERR     "expected": "string",
deliberation-empirica-empirica-1  | [server] 23:48:54.153 ERR     "received": "null",
deliberation-empirica-empirica-1  | [server] 23:48:54.154 ERR     "path": [],
deliberation-empirica-empirica-1  | [server] 23:48:54.155 ERR     "message": "Expected string, received null"
deliberation-empirica-empirica-1  | [server] 23:48:54.155 ERR   }
deliberation-empirica-empirica-1  | [server] 23:48:54.155 ERR ]
deliberation-empirica-empirica-1  | [server] 23:48:54.155 ERR /build/server/node_modules/zod/lib/index.mjs:449
deliberation-empirica-empirica-1  | [server] 23:48:54.155 ERR const error = new ZodError(ctx.common.issues);
deliberation-empirica-empirica-1  | [server] 23:48:54.155 ERR ^
deliberation-empirica-empirica-1  | [server] 23:48:54.155 ERR ZodError: [
deliberation-empirica-empirica-1  | [server] 23:48:54.157 ERR {
deliberation-empirica-empirica-1  | [server] 23:48:54.158 ERR "code": "invalid_type",
deliberation-empirica-empirica-1  | [server] 23:48:54.159 ERR "expected": "string",
deliberation-empirica-empirica-1  | [server] 23:48:54.159 ERR "received": "null",
deliberation-empirica-empirica-1  | [server] 23:48:54.159 ERR "path": [],
deliberation-empirica-empirica-1  | [server] 23:48:54.159 ERR "message": "Expected string, received null"
deliberation-empirica-empirica-1  | [server] 23:48:54.159 ERR }
deliberation-empirica-empirica-1  | [server] 23:48:54.159 ERR ]
deliberation-empirica-empirica-1  | [server] 23:48:54.159 ERR   at g1 (/build/server/node_modules/zod/lib/index.mjs:449:23)
deliberation-empirica-empirica-1  | [server] 23:48:54.160 ERR   at rr.safeParse (/build/server/node_modules/zod/lib/index.mjs:561:16)
deliberation-empirica-empirica-1  | [server] 23:48:54.160 ERR   at rr.parse (/build/server/node_modules/zod/lib/index.mjs:541:29)
deliberation-empirica-empirica-1  | [server] 23:48:54.160 ERR   at <anonymous> (/build/server/node_modules/@empirica/core/src/admin/classic/classic.ts:523:25)
deliberation-empirica-empirica-1  | [server] 23:48:54.160 ERR   at Object.callback (/build/server/node_modules/@empirica/core/src/admin/events.ts:88:11)
deliberation-empirica-empirica-1  | [server] 23:48:54.160 ERR   at Object.next (/build/server/node_modules/@empirica/core/src/admin/cake.ts:309:30)
deliberation-empirica-empirica-1  | [server] [UnhandledPromiseRejection: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason "[object Object]".] {
deliberation-empirica-empirica-1  | [server]   code: 'ERR_UNHANDLED_REJECTION'
deliberation-empirica-empirica-1  | [server] }
```

and:

```bash
deliberation-empirica-empirica-1  | [server] 23:49:22.945 ERR Error caught in "round.start" callback:
deliberation-empirica-empirica-1  | [server] 23:49:23.249 ERR ZodError: [
deliberation-empirica-empirica-1  | [server] 23:49:23.251 ERR   {
deliberation-empirica-empirica-1  | [server] 23:49:23.251 ERR     "code": "invalid_type",
deliberation-empirica-empirica-1  | [server] 23:49:23.251 ERR     "expected": "string",
deliberation-empirica-empirica-1  | [server] 23:49:23.251 ERR     "received": "null",
deliberation-empirica-empirica-1  | [server] 23:49:23.251 ERR     "path": [],
deliberation-empirica-empirica-1  | [server] 23:49:23.251 ERR     "message": "Expected string, received null"
deliberation-empirica-empirica-1  | [server] 23:49:23.251 ERR   }
deliberation-empirica-empirica-1  | [server] 23:49:23.251 ERR ]
deliberation-empirica-empirica-1  | [server] 23:49:23.251 ERR /build/server/node_modules/zod/lib/index.mjs:449
deliberation-empirica-empirica-1  | [server] 23:49:23.251 ERR const error = new ZodError(ctx.common.issues);
deliberation-empirica-empirica-1  | [server] 23:49:23.252 ERR ^
deliberation-empirica-empirica-1  | [server] 23:49:23.252 ERR ZodError: [
deliberation-empirica-empirica-1  | [server] 23:49:23.252 ERR {
deliberation-empirica-empirica-1  | [server] 23:49:23.252 ERR "code": "invalid_type",
deliberation-empirica-empirica-1  | [server] 23:49:23.252 ERR "expected": "string",
deliberation-empirica-empirica-1  | [server] 23:49:23.252 ERR "received": "null",
deliberation-empirica-empirica-1  | [server] 23:49:23.252 ERR "path": [],
deliberation-empirica-empirica-1  | [server] 23:49:23.252 ERR "message": "Expected string, received null"
deliberation-empirica-empirica-1  | [server] 23:49:23.252 ERR }
deliberation-empirica-empirica-1  | [server] 23:49:23.252 ERR ]
deliberation-empirica-empirica-1  | [server] 23:49:23.252 ERR   at g1 (/build/server/node_modules/zod/lib/index.mjs:449:23)
deliberation-empirica-empirica-1  | [server] 23:49:23.252 ERR   at rr.safeParse (/build/server/node_modules/zod/lib/index.mjs:561:16)
deliberation-empirica-empirica-1  | [server] 23:49:23.252 ERR   at rr.parse (/build/server/node_modules/zod/lib/index.mjs:541:29)
deliberation-empirica-empirica-1  | [server] 23:49:23.252 ERR   at <anonymous> (/build/server/node_modules/@empirica/core/src/admin/classic/classic.ts:523:25)
deliberation-empirica-empirica-1  | [server] 23:49:23.253 ERR   at Object.callback (/build/server/node_modules/@empirica/core/src/admin/events.ts:88:11)
deliberation-empirica-empirica-1  | [server] 23:49:23.253 ERR   at Object.next (/build/server/node_modules/@empirica/core/src/admin/cake.ts:309:30)
deliberation-empirica-empirica-1  | [server] 23:49:23.253 ERR   at processTicksAndRejections (node:internal/process/task_queues:96:5)
deliberation-empirica-empirica-1  | [server] [UnhandledPromiseRejection: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason "[object Object]".] {
deliberation-empirica-empirica-1  | [server]   code: 'ERR_UNHANDLED_REJECTION'
deliberation-empirica-empirica-1  | [server] }
```

**Comment by JamesPHoughton** [comment]
Docker container build-249
empirica package 1.0.6

**Comment by JamesPHoughton** [comment]
I'm now thinking more that the `UnhandledPromiseRejection` is a separate issue. I'm running it in our test environment, with extra logging enabled, and not getting any more info in the server logs...

**Comment by npaton** [comment]
I also think the UnhandledPromiseRejection are unrelated. The General Zod errors are asserts I put to verify invariants or conditions that should be met at certain points of the game lifecycle. The fact they are not met can come from a few reasons:
- a bug in tajriba (generally unlikely in this instance)
- a bug in the callbacks server local state management (there could be some ordering issues still)
- a bug in the lifecycle logic (quite possible)
- a bug in the experiment logic when doing lifecycle overrides (possible, and we should be able to catch these and hopefully explain better)

Without a reproducible case, my only option right now is to write tests and try to reproduce. If ever you have a test that systematically, or frequently triggers one of these issues, please let me know.

As for the UnhandledPromiseRejection, those a much more difficult to debug, as we have 0 information. We catch all callback errors, so it's likely to be in the core logic. Again, if you have cases, let me know, otherwise, I'll be working on adding more tests until we have better coverage and can catch these issues.

**Comment by npaton** [comment]
This should be fixed.
