### ISSUE TITLE
Initial server console logs are lost

### ISSUE THREAD

**Issue by JamesPHoughton** [empiricaly/empirica#307]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

If I log something to the console or throw an error in an "onStart" callback:
```js
Empirica.on("start", (ctx) => {
  console.log("On Start callback");
  ctx.globals.set("OnStartRan", new Date(Date.now()).toString());
  throw new Error("test error");
});
```
The message is not displayed to the console:
```bash
(base) jamesphoughton@Jamess-MacBook-Pro-5 prisonersDilemmaDemo % empirica
[server] 
[server]   dist/index.js      741.6kb
[server]   dist/index.js.map    2.9mb
[server] 
[server] ⚡ Done in 61ms

   Empirica (local build) server running:                                             
                                                                                      
      Player  http://localhost:3000                                                   
      Admin   http://localhost:3000/admin    
```
(This is more problematic for the thrown error than the console log)

However, I do know the callbacks ran, because I can see their effects later. For example:
```js
Empirica.on("batch", "status", (ctx, { batch, status }) => {
  console.log("Now: ", new Date(Date.now()).toString());
  console.log("On start ran at:", ctx.globals.get("OnStartRan"));
});
```
yields:
```bash
[server] Now:  Mon May 15 2023 12:24:18 GMT-0400 (Eastern Daylight Time)
[server] On start ran at: Mon May 15 2023 12:24:09 GMT-0400 (Eastern Daylight Time)
```

Interesingly, if I cause the callbacks to be reloaded (e.g. by modifying the callbacks.js and saving it) then the logs and error messages from the "on Start" callback do get displayed (eventually):
```bash
[server] buildscript
[server] building file list ... 
[server] 0 files to consider
[server] 
[server] sent 29 bytes  received 20 bytes  98.00 bytes/sec
[server] total size is 0  speedup is 0.00
[server] 
[server]   dist/index.js      741.4kb
[server]   dist/index.js.map    2.9mb
[server] 
[server] ⚡ Done in 52ms
[server] .empirica path /Users/jamesphoughton/Desktop/experiments/prisonersDilemmaDemo/.empirica
[server] On Start callback
[server] 12:32:14.126 ERR Error caught in "start" callback:
[server] 12:32:14.169 ERR Error: test error
[server] 12:32:14.169 ERR /Users/jamesphoughton/Desktop/experiments/prisonersDilemmaDemo/server/src/callbacks.js:7
[server] 12:32:14.169 ERR throw new Error("test error");
[server] 12:32:14.169 ERR ^
[server] 12:32:14.169 ERR   at Object.callback (/Users/jamesphoughton/Desktop/experiments/prisonersDilemmaDemo/server/src/callbacks.js:7:9)
[server] 12:32:14.170 ERR   at xH.add (/Users/jamesphoughton/Desktop/experiments/prisonersDilemmaDemo/server/node_modules/@empirica/core/src/admin/cake.ts:61:21)
[server] 12:32:14.170 ERR   at <anonymous> (/Users/jamesphoughton/Desktop/experiments/prisonersDilemmaDemo/server/node_modules/@empirica/core/src/admin/runloop.ts:124:23)
[server] 12:32:14.170 ERR   at p (/Users/jamesphoughton/Desktop/experiments/prisonersDilemmaDemo/server/node_modules/rxjs/src/internal/operators/mergeInternals.ts:71:15)
[server] 12:32:14.170 ERR   at v (/Users/jamesphoughton/Desktop/experiments/prisonersDilemmaDemo/server/node_modules/rxjs/src/internal/operators/mergeInternals.ts:121:19)
[server] 12:32:14.170 ERR   at t.onFinalize (/Users/jamesphoughton/Desktop/experiments/prisonersDilemmaDemo/server/node_modules/rxjs/src/internal/operators/mergeInternals.ts:113:48)
[server] 12:32:14.170 ERR   at t.t.unsubscribe (/Users/jamesphoughton/Desktop/experiments/prisonersDilemmaDemo/server/node_modules/rxjs/src/internal/operators/OperatorSubscriber.ts:109:33)
[server] 12:32:14.170 ERR   at t.u._complete (/Users/jamesphoughton/Desktop/experiments/prisonersDilemmaDemo/server/node_modules/rxjs/src/internal/operators/OperatorSubscriber.ts:98:18)
[server] 12:32:14.170 ERR   at t.t.complete (/Users/jamesphoughton/Desktop/experiments/prisonersDilemmaDemo/server/node_modules/rxjs/src/internal/Subscriber.ts:106:12)
[server] 12:32:14.170 ERR   at <anonymous> (/Users/jamesphoughton/Desktop/experiments/prisonersDilemmaDemo/server/node_modules/rxjs/src/internal/observable/innerFrom.ts:90:24)
[server] 12:32:14.172 INF server: started
──────────────────────────────────────────────────────────────────────────────────────
server refreshed                       
```

### Empirica Version

```text
Version: v1.3.2
SHA:     a1c7ead
Branch:  main
Time:    2023-05-14T11:24:08Z

Client:  1.3.2
Server:  1.3.2
```

### What OS are you seeing the problem on?

macOS

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by npaton** [comment]
There is some unnecessary "magic" going on with the logs at the start there. I need to improve that. Meanwhile, you can get back the initial logs with `--log.level debug`.
