### ISSUE TITLE
oplog trailing error with MongoDB atlas

### ISSUE THREAD

**Issue by amaatouq** [empiricaly/empirica#32]
All deployments of Empirica on Galaxy + MongoDB atlas with oplog trailing enabled provides the following error at the end of the game:

```

eevvv
2018-06-15 13:31:00-04:00The game has ended for eAzubigz7MFYGJ4sE
eevvv
2018-06-15 13:31:02-04:00Error in oplog callback MinimongoError: Invalid modifier specified $v
eevvv
2018-06-15 13:31:02-04:00 at MinimongoError (packages/minimongo/common.js:1087:17)
eevvv
2018-06-15 13:31:02-04:00 at Object.keys.forEach.operator (packages/minimongo/local_collection.js:1139:15)
eevvv
2018-06-15 13:31:02-04:00 at Array.forEach (<anonymous>)
eevvv
2018-06-15 13:31:02-04:00 at Function.LocalCollection._modify (packages/minimongo/local_collection.js:1132:27)
eevvv
2018-06-15 13:31:02-04:00 at Matcher.Minimongo.Matcher.canBecomeTrueByModifier (packages/minimongo/minimongo_server.js:128:21)
eevvv
2018-06-15 13:31:02-04:00 at packages/mongo/oplog_observe_driver.js:641:34
eevvv
2018-06-15 13:31:02-04:00 at Object.Meteor._noYieldsAllowed (packages/meteor.js:730:12)
eevvv
2018-06-15 13:31:02-04:00 at OplogObserveDriver._handleOplogEntrySteadyOrFetching (packages/mongo/oplog_observe_driver.js:575:12)
eevvv
2018-06-15 13:31:02-04:00 at packages/mongo/oplog_observe_driver.js:129:20
eevvv
2018-06-15 13:31:02-04:00 at packages/mongo/oplog_observe_driver.js:15:9
eevvv
2018-06-15 13:31:02-04:00 at Object.Meteor._noYieldsAllowed (packages/meteor.js:730:12)
eevvv
2018-06-15 13:31:02-04:00 at packages/mongo/oplog_observe_driver.js:117:16
eevvv
2018-06-15 13:31:02-04:00 at packages/mongo/oplog_tailing.js:100:7
eevvv
2018-06-15 13:31:02-04:00 at runWithEnvironment (packages/meteor.js:1240:24)
eevvv
2018-06-15 13:31:02-04:00 at Object.callback (packages/meteor.js:1253:14)
eevvv
2018-06-15 13:31:02-04:00 at packages/ddp-server/crossbar.js:109:36
eevvv
2018-06-15 13:31:02-04:00 at Array.forEach (<anonymous>)
eevvv
2018-06-15 13:31:02-04:00 at Function._.each._.forEach (packages/underscore.js:139:11)
eevvv
2018-06-15 13:31:02-04:00 at DDPServer._Crossbar.fire (packages/ddp-server/crossbar.js:107:7)
eevvv
2018-06-15 13:31:02-04:00 at packages/mongo/oplog_tailing.js:304:26
eevvv
2018-06-15 13:31:02-04:00 at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1186:15)
eevvv
2018-06-15 13:31:02-04:00 at packages/meteor.js:502:25
```

The Galaxy Configuration (could it be the problem in the `MONGO_OPLOG_URL`) :
```
{
  "galaxy.meteor.com": {
    "env": {
      "MONGO_URL":
        "mongodb://admin:<PASSWORD>@interactive-estimation-shard-00-00-b9hsg.mongodb.net:27017,interactive-estimation-shard-00-01-b9hsg.mongodb.net:27017,interactive-estimation-shard-00-02-b9hsg.mongodb.net:27017/RME?ssl=true&replicaSet=interactive-estimation-shard-0&authSource=admin&retryWrites=true",
      "MONGO_OPLOG_URL":
        "mongodb://oploguser:<PASSWORD>@interactive-estimation-shard-00-00-b9hsg.mongodb.net:27017,interactive-estimation-shard-00-01-b9hsg.mongodb.net:27017,interactive-estimation-shard-00-02-b9hsg.mongodb.net:27017/local?ssl=true&replicaSet=interactive-estimation-shard-0&authSource=admin"
    }
  },
  "public": {
    "playerIdParam": "workerId",
    "playerIdParamExclusive": false,
    "debug_newPlayer": false,
    "debug_resetSession": false,
    "debug_resetDatabase": true,
    "debug_gameDebugMode": false
  }
}

```

**Comment by amaatouq** [comment]
Possible solutions are discussed here: https://forums.meteor.com/t/error-in-oplog-callback-minimongoerror-invalid-modifier-specified-v/42718/6

and here: https://atmospherejs.com/natestrauser/publish-performant-counts 

It seems that removing `tmeasday:publish-counts` did the trick for some people who faced the same problem.

**Comment by npaton** [comment]
That thread continues on to say it did not actually fix the problem. The other issue is that that package they propose works differently and does not give timely and accurate counts, so it wouldn't work for us. I'd like to understand the problem better before _fixing_ it. I don't actually know what the consequence of this issue is yet. I am also going to update Meteor, which might help with this issue as it updates pretty much everything (Mongo lib, live queries, etc.)

**Comment by npaton** [comment]
I updated to Meteor 1.7.0.3. I'd like to see if that helps with this issue.
