### ISSUE TITLE
Deploying default app error `cyclic dependency detected`

### ISSUE THREAD

**Issue by amaatouq** [empiricaly/empirica#34]
Deploying the default Empirica App gives the following error:

```
2018-06-18 14:01:39-04:00/app/bundle/programs/server/node_modules/fibers/future.js:313
7mtnd
2018-06-18 14:01:39-04:00	throw(ex);
7mtnd
2018-06-18 14:01:39-04:00	^
7mtnd
2018-06-18 14:01:39-04:00
7mtnd
2018-06-18 14:01:39-04:00Error: cyclic dependency detected
7mtnd
2018-06-18 14:01:39-04:00 at serializeObject (/app/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/bson/lib/bson/parser/serializer.js:331:34)
7mtnd
2018-06-18 14:01:39-04:00 at serializeInto (/app/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/bson/lib/bson/parser/serializer.js:934:17)
7mtnd
2018-06-18 14:01:39-04:00 at serializeObject (/app/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/bson/lib/bson/parser/serializer.js:345:18)
7mtnd
2018-06-18 14:01:39-04:00 at serializeInto (/app/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/bson/lib/bson/parser/serializer.js:934:17)
7mtnd
2018-06-18 14:01:39-04:00 at serializeObject (/app/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/bson/lib/bson/parser/serializer.js:345:18)
7mtnd
2018-06-18 14:01:39-04:00 at serializeInto (/app/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/bson/lib/bson/parser/serializer.js:934:17)
7mtnd
2018-06-18 14:01:39-04:00 at serializeObject (/app/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/bson/lib/bson/parser/serializer.js:345:18)
7mtnd
2018-06-18 14:01:39-04:00 at serializeInto (/app/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/bson/lib/bson/parser/serializer.js:934:17)
7mtnd
2018-06-18 14:01:39-04:00 at serializeObject (/app/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/bson/lib/bson/parser/serializer.js:345:18)
7mtnd
2018-06-18 14:01:39-04:00 at serializeInto (/app/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/bson/lib/bson/parser/serializer.js:934:17)
7mtnd
2018-06-18 14:01:39-04:00 at serializeObject (/app/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/bson/lib/bson/parser/serializer.js:345:18)
7mtnd
2018-06-18 14:01:39-04:00 at serializeInto (/app/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/bson/lib/bson/parser/serializer.js:934:17)
7mtnd
2018-06-18 14:01:39-04:00 at serializeObject (/app/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/bson/lib/bson/parser/serializer.js:345:18)
7mtnd
2018-06-18 14:01:39-04:00 at serializeInto (/app/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/bson/lib/bson/parser/serializer.js:934:17)
7mtnd
2018-06-18 14:01:39-04:00 at serializeObject (/app/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/bson/lib/bson/parser/serializer.js:345:18)
7mtnd
2018-06-18 14:01:39-04:00 at serializeInto (/app/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/bson/lib/bson/parser/serializer.js:934:17)
```

Details can be found on the Galaxy container.

**Comment by amaatouq** [comment]
Two thoughts from https://github.com/Automattic/mongoose/issues/6109:
- removing `&retryWrites=true` from the atlas URI fixes the problem
- the fundamental problem has to do with trying to create an index on `_id`

**Comment by amaatouq** [comment]
At least we need to document this.
