### ISSUE TITLE
[Bug Report] Batches gone missing but game progressing normally

### ISSUE THREAD

**Issue by darthkenobi5319** [empiricaly/empirica#425]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

the batches have gone missing after admin page has been refreshed so I cannot monitor the games (The players page is normal, and players are playing the game normally) 

### Steps To Reproduce

1. Setup a game with a batch (any batch, for our test approximately 40 players and 15 players all had the same problem)
2. The game runs and participants play, After a period, all batches disappear from the admin panel (but games are running as usual without failure)
3. You may click on 'players' and see the players are normal, online and in the platform. But batches are nowhere to be seen
4. New batches created at this point also cannot be seen
![image](https://github.com/empiricaly/empirica/assets/43033983/797059ba-eb0b-4eac-9d00-f42bd25dc9d4)
![image_720](https://github.com/empiricaly/empirica/assets/43033983/9332e5d8-95ff-4abe-89e7-267d782e2578)

### Empirica Version

```text
Version: v1.8.1
SHA: e4be405
Branch: main
```

### What OS are you seeing the problem on?

Windows

### What browser are you seeing the problem on?

Microsoft Edge

### Anything else?

[out231010main.txt](https://github.com/empiricaly/empirica/files/12865122/out231010main.txt)
[out231010backup.txt](https://github.com/empiricaly/empirica/files/12865123/out231010backup.txt)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by npaton** [comment]
I apologize, I missed this issue previously. I can see in your logs an issue that has been fixed in more recent releases (transition step: invalid state). You might also want to look into from your experiment's code:

```
llm response is not a valid json
TypeError: i.to.split is not a function
    at NY (/tmp/ea41cecfe5ba045e/src/gpt/prompts/responseHandler.js:24:58)
    at sv.callForAction (/tmp/ea41cecfe5ba045e/src/gpt/GPTAgent.jsx:157:15)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at ZCe (/tmp/ea41cecfe5ba045e/src/callbacks.js:206:5)
```

As for the missing batches in the admin, that does sounds like an issue that is still existing, since it was reported again in #469. If you happen to still have the `tajriba.json` (found at `.empirica/local/tajriba.json`) file where this problem was happening, I'd appreciate if you could share it (you can DM me on Slack if it's confidential). Thank you, and, again, sorry for the lack of an earlier response. 🙏
