### ISSUE TITLE
cannot assign player to an ended game

### ISSUE THREAD

**Issue by npaton** [empiricaly/empirica#462]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

![image_720](https://github.com/empiricaly/empirica/assets/9678/9482023a-b027-44e3-b514-0d4062d29101)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by aliciamchen** [comment]
I'm also getting this issue, in `1.8.12`.

```
23:42:29.872 ERR Error caught in "player" callback:
23:42:30.022 ERR Error: cannot assign player to ended Game
23:42:30.022 ERR   at ag.assignPlayer (/tmp/2fe66e9b1d711942/node_modules/@empirica/core/src/admin/classic/models.ts:180:13)
23:42:30.022 ERR   at l (/tmp/2fe66e9b1d711942/node_modules/@empirica/core/src/admin/classic/classic.ts:110:20)
23:42:30.022 ERR   at Object.callback (/tmp/2fe66e9b1d711942/node_modules/@empirica/core/src/admin/classic/classic.ts:241:15)
23:42:30.022 ERR   at <anonymous> (/tmp/2fe66e9b1d711942/node_modules/@empirica/core/src/admin/cake.ts:229:30)
23:42:30.023 ERR   at g (/tmp/2fe66e9b1d711942/node_modules/rxjs/src/internal/operators/mergeInternals.ts:71:15)
23:42:30.023 ERR   at v (/tmp/2fe66e9b1d711942/node_modules/rxjs/src/internal/operators/mergeInternals.ts:53:58)
23:42:30.023 ERR   at t.l._next (/tmp/2fe66e9b1d711942/node_modules/rxjs/src/internal/operators/OperatorSubscriber.ts:70:13)
23:42:30.023 ERR   at t.t.next (/tmp/2fe66e9b1d711942/node_modules/rxjs/src/internal/Subscriber.ts:75:12)
23:42:30.023 ERR   at <anonymous> (/tmp/2fe66e9b1d711942/node_modules/rxjs/src/internal/Subject.ts:68:20)
23:42:30.023 ERR   at Object.vH (/tmp/2fe66e9b1d711942/node_modules/rxjs/src/internal/util/errorContext.ts:29:5)
```

**Comment by aliciamchen** [comment]
I also get this error with the "participant connect" callback: 

```
23:45:48.548 ERR Error caught in "participant connect" callback:
23:45:48.699 ERR Error: cannot assign player to ended Game
23:45:48.699 ERR   at ag.assignPlayer (/tmp/2fe66e9b1d711942/node_modules/@empirica/core/src/admin/classic/models.ts:180:13)
23:45:48.699 ERR   at l (/tmp/2fe66e9b1d711942/node_modules/@empirica/core/src/admin/classic/classic.ts:110:20)
23:45:48.700 ERR   at Object.callback (/tmp/2fe66e9b1d711942/node_modules/@empirica/core/src/admin/classic/classic.ts:218:15)
23:45:48.700 ERR   at <anonymous> (/tmp/2fe66e9b1d711942/node_modules/@empirica/core/src/admin/cake.ts:428:30)
23:45:48.700 ERR   at g (/tmp/2fe66e9b1d711942/node_modules/rxjs/src/internal/operators/mergeInternals.ts:71:15)
23:45:48.700 ERR   at v (/tmp/2fe66e9b1d711942/node_modules/rxjs/src/internal/operators/mergeInternals.ts:53:58)
23:45:48.700 ERR   at t.l._next (/tmp/2fe66e9b1d711942/node_modules/rxjs/src/internal/operators/OperatorSubscriber.ts:70:13)
23:45:48.700 ERR   at t.t.next (/tmp/2fe66e9b1d711942/node_modules/rxjs/src/internal/Subscriber.ts:75:12)
23:45:48.700 ERR   at <anonymous> (/tmp/2fe66e9b1d711942/node_modules/rxjs/src/internal/Subject.ts:68:20)
23:45:48.700 ERR   at Object.vH (/tmp/2fe66e9b1d711942/node_modules/rxjs/src/internal/util/errorContext.ts:29:5)
```

**Comment by aliciamchen** [comment]
And the "batch.status" callback: 

```
00:51:04.950 ERR Error caught in "batch.status" callback:
00:51:05.261 ERR Error: cannot assign player to ended Game
00:51:05.261 ERR   at ag.assignPlayer (/tmp/2fe66e9b1d711942/node_modules/@empirica/core/src/admin/classic/models.ts:180:13)
00:51:05.262 ERR   at l (/tmp/2fe66e9b1d711942/node_modules/@empirica/core/src/admin/classic/classic.ts:110:20)
00:51:05.262 ERR   at <anonymous> (/tmp/2fe66e9b1d711942/node_modules/@empirica/core/src/admin/classic/classic.ts:308:23)
00:51:05.262 ERR   at runMicrotasks (<anonymous>)
00:51:05.262 ERR   at processTicksAndRejections (node:internal/process/task_queues:96:5)
00:51:05.262 ERR   at Object.callback (/tmp/2fe66e9b1d711942/node_modules/@empirica/core/src/admin/events.ts:91:5)
00:51:05.262 ERR   at Object.next (/tmp/2fe66e9b1d711942/node_modules/@empirica/core/src/admin/cake.ts:322:15)
```

**Comment by aliciamchen** [comment]
Some participants have reported logging on and getting the spinny circle for a long time (i.e. game not starting for them). Maybe this is related?

**Comment by aliciamchen** [comment]
FYI I don't seem to get this error when I run only one game per batch.

**Comment by npaton** [comment]
Thank you, that's very helpful.

**Comment by npaton** [comment]
I believe this was fixes with some race condition fixes. Please reopen if you encounter it still.
