### ISSUE TITLE
Error caught in `round.start` callback

### ISSUE THREAD

**Issue by aliciamchen** [empiricaly/empirica#467]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

I got this error a few minutes after I launched my experiment. It doesn't prevent the experiment from progressing, but perhaps it is related to #466 

### Empirica Version

```text
Version: v1.8.11
SHA:     fce31f9
Build:   154
Branch:  main
Time:    2023-12-20T10:26:18Z
```

### What OS are you seeing the problem on?

macOS

### Relevant log output

```shell
20:03:38.142 ERR Error caught in "round.start" callback:
20:03:38.383 ERR TypeError: Cannot read properties of undefined (reading 'set')
20:03:38.383 ERR   at <anonymous> (/tmp/ba2f298c74fd691b/src/callbacks.js:65:17)
20:03:38.383 ERR   at <anonymous> (/tmp/ba2f298c74fd691b/node_modules/@empirica/core/src/admin/classic/proxy.ts:54:9)
20:03:38.383 ERR   at Object.callback (/tmp/ba2f298c74fd691b/node_modules/@empirica/core/src/admin/events.ts:91:11)
20:03:38.383 ERR   at Object.next (/tmp/ba2f298c74fd691b/node_modules/@empirica/core/src/admin/cake.ts:322:30)
20:03:38.383 ERR   at runMicrotasks (<anonymous>)
20:03:38.383 ERR   at processTicksAndRejections (node:internal/process/task_queues:96:5)
20:03:38.385 ERR Error caught in "round.start" callback:
20:03:38.522 ERR ZodError: [
20:03:38.522 ERR   {
20:03:38.522 ERR     "code": "invalid_type",
20:03:38.522 ERR     "expected": "string",
20:03:38.522 ERR     "received": "undefined",
20:03:38.522 ERR     "path": [],
20:03:38.522 ERR     "message": "Required"
20:03:38.522 ERR   }
20:03:38.522 ERR ]
20:03:38.522 ERR ZodError: [
20:03:38.523 ERR {
20:03:38.523 ERR "code": "invalid_type",
20:03:38.523 ERR "expected": "string",
20:03:38.523 ERR "received": "undefined",
20:03:38.523 ERR "path": [],
20:03:38.523 ERR "message": "Required"
20:03:38.523 ERR }
20:03:38.523 ERR ]
20:03:38.523 ERR   at vb (/tmp/ba2f298c74fd691b/node_modules/zod/lib/index.mjs:449:23)
20:03:38.523 ERR   at Ai.safeParse (/tmp/ba2f298c74fd691b/node_modules/zod/lib/index.mjs:561:16)
20:03:38.523 ERR   at Ai.parse (/tmp/ba2f298c74fd691b/node_modules/zod/lib/index.mjs:541:29)
20:03:38.523 ERR   at <anonymous> (/tmp/ba2f298c74fd691b/node_modules/@empirica/core/src/admin/classic/classic.ts:560:24)
20:03:38.523 ERR   at Object.callback (/tmp/ba2f298c74fd691b/node_modules/@empirica/core/src/admin/events.ts:91:11)
20:03:38.523 ERR   at Object.next (/tmp/ba2f298c74fd691b/node_modules/@empirica/core/src/admin/cake.ts:322:30)
20:03:38.523 ERR   at runMicrotasks (<anonymous>)
20:03:38.523 ERR   at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by npaton** [comment]
This one is odd, I still need to look further into it.

**Comment by aliciamchen** [comment]
Thank you! If it helps, my experiment code is at https://github.com/aliciamchen/hierarchical-teaching/tree/main/experiments/exp3
