### ISSUE TITLE
[GraphQL] add link: duplicate node id

### ISSUE THREAD

**Issue by frasalvi** [empiricaly/empirica#477]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

I've been getting an `Unhandled Promise Rejection. Reason:  [t [CombinedError]: [GraphQL] add link: duplicate node id]` error twice now, in a random fashion (so, not reproducible...), in a promise within `Empirica.onStageEnded`. This does not make the server crash, but the games where this happens do not behave as intended.

### Empirica Version

```text
Version: v1.8.12
SHA:     656d19b
Build:   159
Branch:  main
Time:    2023-12-26T07:14:40Z
```

### What OS are you seeing the problem on?

Linux

### What browser are you seeing the problem on?

Chrome

### Relevant log output

```shell
Unhandled Promise Rejection. Reason:  [t [CombinedError]: [GraphQL] add link: duplicate node id] {
  graphQLErrors: [
    ga [GraphQLError]: add link: duplicate node id
        at TW (/tmp/6f4f016c6f6c7f55/node_modules/@urql/core/src/utils/error.ts:24:10)
        at Array.map (<anonymous>)
        at t (/tmp/6f4f016c6f6c7f55/node_modules/@urql/core/src/utils/error.ts:61:5)
        at x1 (/tmp/6f4f016c6f6c7f55/node_modules/@urql/core/src/utils/result.ts:22:15)
        at Object.next (/tmp/6f4f016c6f6c7f55/node_modules/@urql/core/src/exchanges/subscription.ts:82:15)
        at Object.42cbf88e-bc76-4921-ba7d-9adac8c16d2b (/tmp/6f4f016c6f6c7f55/node_modules/graphql-ws/lib/client.mjs:361:42)
        at emit (/tmp/6f4f016c6f6c7f55/node_modules/graphql-ws/lib/client.mjs:77:94)
        at Object.emit (/tmp/6f4f016c6f6c7f55/node_modules/graphql-ws/lib/client.mjs:104:21)
        at Pe.X.onmessage (/tmp/6f4f016c6f6c7f55/node_modules/graphql-ws/lib/client.mjs:200:29)
        at Yh (/tmp/6f4f016c6f6c7f55/node_modules/ws/lib/event-target.js:290:14) {
      path: [Array],
      locations: undefined,
      extensions: {}
    }
  ],
  networkError: undefined,
  response: undefined
}
22:42:43.258 WRN failed load: [GraphQL] add link: duplicate node id
22:42:43.258 WRN failed load: [GraphQL] add link: duplicate node id
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by npaton** [comment]
This should be fixed in the latest release (1.9.0).
