### ISSUE TITLE
Error in galaxy logs .. no apparent effect on the user

### ISSUE THREAD

**Issue by amaatouq** [empiricaly/empirica#55]
I've been noticing the following error in the logs that doesn't seem to have an effect on the user side of things. 

```

p61tp
2018-07-17 09:44:58-04:00Exception in setTimeout callback: { MongoError: cursor id 100607005356 not found
p61tp
2018-07-17 09:44:58-04:00 at /app/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/connection/pool.js:598:61
p61tp
2018-07-17 09:44:58-04:00 at authenticateStragglers (/app/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/connection/pool.js:516:16)
p61tp
2018-07-17 09:44:58-04:00 at Connection.messageHandler (/app/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/connection/pool.js:552:5)
p61tp
2018-07-17 09:44:58-04:00 at emitMessageHandler (/app/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/connection/connection.js:309:10)
p61tp
2018-07-17 09:44:58-04:00 at TLSSocket.<anonymous> (/app/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/connection/connection.js:452:17)
p61tp
2018-07-17 09:44:58-04:00 at emitOne (events.js:116:13)
p61tp
2018-07-17 09:44:58-04:00 at TLSSocket.emit (events.js:211:7)
p61tp
2018-07-17 09:44:58-04:00 at addChunk (_stream_readable.js:263:12)
p61tp
2018-07-17 09:44:58-04:00 at readableAddChunk (_stream_readable.js:250:11)
p61tp
2018-07-17 09:44:58-04:00 at TLSSocket.Readable.push (_stream_readable.js:208:10)
p61tp
2018-07-17 09:44:58-04:00 at TLSWrap.onread (net.js:597:20)
p61tp
2018-07-17 09:44:58-04:00 => awaited here:
p61tp
2018-07-17 09:44:58-04:00 at Function.Promise.await (/app/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:56:12)
p61tp
2018-07-17 09:44:58-04:00 at Promise.asyncApply (packages/mongo/mongo_driver.js:1034:11)
p61tp
2018-07-17 09:44:58-04:00 at /app/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40
p61tp
2018-07-17 09:44:58-04:00 => awaited here:
p61tp
2018-07-17 09:44:58-04:00 at Promise.await (/app/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:60:12)
p61tp
2018-07-17 09:44:58-04:00 at SynchronousCursor._nextObject (packages/mongo/mongo_driver.js:1083:12)
p61tp
2018-07-17 09:44:58-04:00 at SynchronousCursor.forEach (packages/mongo/mongo_driver.js:1097:22)
p61tp
2018-07-17 09:44:58-04:00 at Cursor.(anonymous function) [as forEach] (packages/mongo/mongo_driver.js:879:44)
p61tp
2018-07-17 09:44:58-04:00 at Object.task (imports/core/api/game-lobbies/server/cron.js:92:29)
p61tp
2018-07-17 09:44:58-04:00 at run (imports/core/startup/server/cron.js:53:14)
p61tp
2018-07-17 09:44:58-04:00 at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1189:12)
p61tp
2018-07-17 09:44:58-04:00 at packages/meteor.js:505:25
p61tp
2018-07-17 09:44:58-04:00 at runWithEnvironment (packages/meteor.js:1241:24)
p61tp
2018-07-17 09:44:58-04:00 name: 'MongoError',
p61tp
2018-07-17 09:44:58-04:00 message: 'cursor id 100607005356 not found',
p61tp
2018-07-17 09:44:58-04:00 ok: 0,
p61tp
2018-07-17 09:44:58-04:00 errmsg: 'cursor id 100607005356 not found',
p61tp
2018-07-17 09:44:58-04:00 code: 43,
p61tp
2018-07-17 09:44:58-04:00 codeName: 'CursorNotFound',
p61tp
2018-07-17 09:44:58-04:00 operationTime: Timestamp { _bsontype: 'Timestamp', low_: 1, high_: 1531835090 },
p61tp
2018-07-17 09:44:58-04:00 '$clusterTime':
p61tp
2018-07-17 09:44:58-04:00 { clusterTime: Timestamp { _bsontype: 'Timestamp', low_: 1, high_: 1531835090 },
p61tp
2018-07-17 09:44:58-04:00 signature: { hash: [Object], keyId: [Object] } } }
```

I wonder if it is related to the problem that we had before where we had the last round to be repeated infinitely (i.e., we check the batch rather than the game is done).

**Comment by npaton** [comment]
From the logs and not seeing further issues with users, I believe this is just a disconnection issue and that the standard reconnection mechanisms are doing their job.
