### ISSUE TITLE
Error in starting empirica server with existing tajriba.json file

### ISSUE THREAD

**Issue by devonrojas** [empiricaly/empirica#560]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

When going to serve my bundled empirica project (after the first initial serve), I get a "connection refused" error on port 3000 that prevents the empirica server from starting correctly. However, after some time, the server is able to run successfully. I have verified that there are no other processes using port 3000 at the time of running the command.

The only solution I've found is to delete the tajriba.json file and do a fresh start of the server.

### Steps To Reproduce

1. Bundle empirica project using `empirica bundle`
2. Serve project using `empirica serve`
3. Run a batch of game(s)
4. Close server
5. Restart server using `empirica serve`

### Empirica Version

```text
Version: v1.11.2
SHA:     0cf63f4
Build:   216
Branch:  main
Time:    2024-04-21T05:45:28Z

Client:  1.11.2
Server:  1.11.2
```

### What OS are you seeing the problem on?

Linux

### What browser are you seeing the problem on?

Does not apply

### Relevant log output

```shell
22:08:18.554 ERR connection error Ds {
  [Symbol(kTarget)]: ye {
    _events: [Object: null prototype] {
      error: [Function],
      close: [Function],
      open: [Function],
      message: [Function]
    },
    _eventsCount: 4,
    _maxListeners: undefined,
    _binaryType: 'nodebuffer',
    _closeCode: 1006,
    _closeFrameReceived: false,
    _closeFrameSent: false,
    _closeMessage: <Buffer >,
    _closeTimer: null,
    _extensions: {},
    _paused: false,
    _protocol: '',
    _readyState: 2,
    _receiver: null,
    _sender: null,
    _socket: null,
    _bufferedAmount: 0,
    _isServer: false,
    _redirects: 0,
    _autoPong: true,
    _url: 'ws://localhost:3000/query',
    _req: null,
    [Symbol(kCapture)]: false
  },
  [Symbol(kType)]: 'error',
  [Symbol(kError)]: Error: connect ECONNREFUSED 127.0.0.1:3000
      at __node_internal_captureLargerStackTrace (node:internal/errors:477:5)
      at __node_internal_exceptionWithHostPort (node:internal/errors:655:12)
      at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1247:16) {
    errno: -111,
    code: 'ECONNREFUSED',
    syscall: 'connect',
    address: '127.0.0.1',
    port: 3000
  },
  [Symbol(kMessage)]: 'connect ECONNREFUSED 127.0.0.1:3000'
}
22:08:20.219 ERR connection error Ds {
  [Symbol(kTarget)]: ye {
    _events: [Object: null prototype] {
      error: [Function],
      close: [Function],
      open: [Function],
      message: [Function]
    },
    _eventsCount: 4,
    _maxListeners: undefined,
    _binaryType: 'nodebuffer',
    _closeCode: 1006,
    _closeFrameReceived: false,
    _closeFrameSent: false,
    _closeMessage: <Buffer >,
    _closeTimer: null,
    _extensions: {},
    _paused: false,
    _protocol: '',
    _readyState: 2,
    _receiver: null,
    _sender: null,
    _socket: null,
    _bufferedAmount: 0,
    _isServer: false,
    _redirects: 0,
    _autoPong: true,
    _url: 'ws://localhost:3000/query',
    _req: null,
    [Symbol(kCapture)]: false
  },
  [Symbol(kType)]: 'error',
  [Symbol(kError)]: Error: connect ECONNREFUSED 127.0.0.1:3000
      at __node_internal_captureLargerStackTrace (node:internal/errors:477:5)
      at __node_internal_exceptionWithHostPort (node:internal/errors:655:12)
      at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1247:16) {
    errno: -111,
    code: 'ECONNREFUSED',
    syscall: 'connect',
    address: '127.0.0.1',
    port: 3000
  },
  [Symbol(kMessage)]: 'connect ECONNREFUSED 127.0.0.1:3000'
}
22:08:25.184 ERR connection error Ds {
  [Symbol(kTarget)]: ye {
    _events: [Object: null prototype] {
      error: [Function],
      close: [Function],
      open: [Function],
      message: [Function]
    },
    _eventsCount: 4,
    _maxListeners: undefined,
    _binaryType: 'nodebuffer',
    _closeCode: 1006,
    _closeFrameReceived: false,
    _closeFrameSent: false,
    _closeMessage: <Buffer >,
    _closeTimer: null,
    _extensions: {},
    _paused: false,
    _protocol: '',
    _readyState: 2,
    _receiver: null,
    _sender: null,
    _socket: null,
    _bufferedAmount: 0,
    _isServer: false,
    _redirects: 0,
    _autoPong: true,
    _url: 'ws://localhost:3000/query',
    _req: null,
    [Symbol(kCapture)]: false
  },
  [Symbol(kType)]: 'error',
  [Symbol(kError)]: Error: connect ECONNREFUSED 127.0.0.1:3000
      at __node_internal_captureLargerStackTrace (node:internal/errors:477:5)
      at __node_internal_exceptionWithHostPort (node:internal/errors:655:12)
      at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1247:16) {
    errno: -111,
    code: 'ECONNREFUSED',
    syscall: 'connect',
    address: '127.0.0.1',
    port: 3000
  },
  [Symbol(kMessage)]: 'connect ECONNREFUSED 127.0.0.1:3000'
}
22:08:31.710 ERR connection error Ds {
  [Symbol(kTarget)]: ye {
    _events: [Object: null prototype] {
      error: [Function],
      close: [Function],
      open: [Function],
      message: [Function]
    },
    _eventsCount: 4,
    _maxListeners: undefined,
    _binaryType: 'nodebuffer',
    _closeCode: 1006,
    _closeFrameReceived: false,
    _closeFrameSent: false,
    _closeMessage: <Buffer >,
    _closeTimer: null,
    _extensions: {},
    _paused: false,
    _protocol: '',
    _readyState: 2,
    _receiver: null,
    _sender: null,
    _socket: null,
    _bufferedAmount: 0,
    _isServer: false,
    _redirects: 0,
    _autoPong: true,
    _url: 'ws://localhost:3000/query',
    _req: null,
    [Symbol(kCapture)]: false
  },
  [Symbol(kType)]: 'error',
  [Symbol(kError)]: Error: connect ECONNREFUSED 127.0.0.1:3000
      at __node_internal_captureLargerStackTrace (node:internal/errors:477:5)
      at __node_internal_exceptionWithHostPort (node:internal/errors:655:12)
      at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1247:16) {
    errno: -111,
    code: 'ECONNREFUSED',
    syscall: 'connect',
    address: '127.0.0.1',
    port: 3000
  },
  [Symbol(kMessage)]: 'connect ECONNREFUSED 127.0.0.1:3000'
}
22:08:43.464 INF server: started
```

### Anything else?

Server Information:
 Static hostname: XXXXX
       Icon name: computer-vm
         Chassis: vm
      Machine ID: XXXXXX
         Boot ID: XXXXXXX
  Virtualization: amazon
Operating System: Ubuntu 22.04.3 LTS
          Kernel: Linux 6.5.0-1018-aws
    Architecture: x86-64
 Hardware Vendor: Amazon EC2
  Hardware Model: t3a.medium

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by npaton** [comment]
Thank you for the report. I have not had the chance to look into this yet but I will as soon as possible.

**Comment by npaton** [comment]
Sorry for the delay. I'm thinking the server is taking some time to initialize and the callbacks are attempting to connect to it too early. Does the system work once the error messages subside? It looks like it's taking 15-20s for the server to start in this case, which can happen if the tajriba file starts to be a bit large (it can grow quite quickly when storing very frequent events such as mouse movements of the players).

**Comment by lenardst** [comment]
I faced the same error. While the server initially worked after the error, it broke down later during the experiment. What worked for me was deleting the .empirica/local/tajriba.json file after copying it somewhere else (https://docs.empirica.ly/guides/deploying-my-experiment).

**Comment by npaton** [comment]
Thank you for the report. Did you see any other logs? Presumably, the api server must be having a problem id the callback server can't connect to it.

**Comment by coderinblack08** [comment]
Hey, facing the same issue.

Clearing the tajriba and restarting the server seemed to work initially, but after ~10 users, we faced the 1006 web socket error every single time, which caused users to see a loading spinner after being ID-ed.

Here is the error log, same error as above:
```
Mar 18 01:47:34 ubuntu-s-1vcpu-512mb-10gb-sfo3-01 empirica[9735]: 01:47:34.984 ERR connection error Ds {
Mar 18 01:47:34 ubuntu-s-1vcpu-512mb-10gb-sfo3-01 empirica[9735]:   [Symbol(kTarget)]: <ref *1> ye {
Mar 18 01:47:34 ubuntu-s-1vcpu-512mb-10gb-sfo3-01 empirica[9735]:     _events: [Object: null prototype] {
Mar 18 01:47:34 ubuntu-s-1vcpu-512mb-10gb-sfo3-01 empirica[9735]:       error: [Function],
Mar 18 01:47:34 ubuntu-s-1vcpu-512mb-10gb-sfo3-01 empirica[9735]:       close: [Function],
Mar 18 01:47:34 ubuntu-s-1vcpu-512mb-10gb-sfo3-01 empirica[9735]:       open: [Function],
Mar 18 01:47:34 ubuntu-s-1vcpu-512mb-10gb-sfo3-01 empirica[9735]:       message: [Function]
Mar 18 01:47:34 ubuntu-s-1vcpu-512mb-10gb-sfo3-01 empirica[9735]:     },
Mar 18 01:47:34 ubuntu-s-1vcpu-512mb-10gb-sfo3-01 empirica[9735]:     _eventsCount: 4,
Mar 18 01:47:34 ubuntu-s-1vcpu-512mb-10gb-sfo3-01 empirica[9735]:     _maxListeners: undefined,
Mar 18 01:47:34 ubuntu-s-1vcpu-512mb-10gb-sfo3-01 empirica[9735]:     _binaryType: 'nodebuffer',
Mar 18 01:47:34 ubuntu-s-1vcpu-512mb-10gb-sfo3-01 empirica[9735]:     _closeCode: 1006,
Mar 18 01:47:34 ubuntu-s-1vcpu-512mb-10gb-sfo3-01 empirica[9735]:     _closeFrameReceived: false,
Mar 18 01:47:34 ubuntu-s-1vcpu-512mb-10gb-sfo3-01 empirica[9735]:     _closeFrameSent: false,
Mar 18 01:47:34 ubuntu-s-1vcpu-512mb-10gb-sfo3-01 empirica[9735]:     _closeMessage: <Buffer >,
Mar 18 01:47:34 ubuntu-s-1vcpu-512mb-10gb-sfo3-01 empirica[9735]:     _closeTimer: null,
Mar 18 01:47:34 ubuntu-s-1vcpu-512mb-10gb-sfo3-01 empirica[9735]:     _extensions: { 'permessage-deflate': [X0] },
Mar 18 01:47:34 ubuntu-s-1vcpu-512mb-10gb-sfo3-01 empirica[9735]:     _paused: false,
Mar 18 01:47:34 ubuntu-s-1vcpu-512mb-10gb-sfo3-01 empirica[9735]:     _protocol: 'graphql-transport-ws',
Mar 18 01:47:34 ubuntu-s-1vcpu-512mb-10gb-sfo3-01 empirica[9735]:     _readyState: 2,
Mar 18 01:47:34 ubuntu-s-1vcpu-512mb-10gb-sfo3-01 empirica[9735]:     _receiver: a2 {
Mar 18 01:47:34 ubuntu-s-1vcpu-512mb-10gb-sfo3-01 empirica[9735]:       _writableState: [WritableState],
Mar 18 01:47:34 ubuntu-s-1vcpu-512mb-10gb-sfo3-01 empirica[9735]:       _events: [Object: null prototype],
Mar 18 01:47:34 ubuntu-s-1vcpu-512mb-10gb-sfo3-01 empirica[9735]:       _eventsCount: 7,
Mar 18 01:47:34 ubuntu-s-1vcpu-512mb-10gb-sfo3-01 empirica[9735]:       _maxListeners: undefined,
Mar 18 01:47:34 ubuntu-s-1vcpu-512mb-10gb-sfo3-01 empirica[9735]:       _allowSynchronousEvents: false,
Mar 18 01:47:34 ubuntu-s-1vcpu-512mb-10gb-sfo3-01 empirica[9735]:       _binaryType: 'nodebuffer',
Mar 18 01:47:34 ubuntu-s-1vcpu-512mb-10gb-sfo3-01 empirica[9735]:       _extensions: [Object],
Mar 18 01:47:34 ubuntu-s-1vcpu-512mb-10gb-sfo3-01 empirica[9735]:       _isServer: false,
Mar 18 01:47:34 ubuntu-s-1vcpu-512mb-10gb-sfo3-01 empirica[9735]:       _maxPayload: 104857600,
Mar 18 01:47:34 ubuntu-s-1vcpu-512mb-10gb-sfo3-01 empirica[9735]:       _skipUTF8Validation: false,
Mar 18 01:47:34 ubuntu-s-1vcpu-512mb-10gb-sfo3-01 empirica[9735]:       _bufferedBytes: 0,
Mar 18 01:47:34 ubuntu-s-1vcpu-512mb-10gb-sfo3-01 empirica[9735]:       _buffers: [],
Mar 18 01:47:34 ubuntu-s-1vcpu-512mb-10gb-sfo3-01 empirica[9735]:       _compressed: true,
Mar 18 01:47:34 ubuntu-s-1vcpu-512mb-10gb-sfo3-01 empirica[9735]:       _payloadLength: 20,
Mar 18 01:47:34 ubuntu-s-1vcpu-512mb-10gb-sfo3-01 empirica[9735]:       _mask: undefined,
Mar 18 01:47:34 ubuntu-s-1vcpu-512mb-10gb-sfo3-01 empirica[9735]:       _fragmented: 0,
Mar 18 01:47:34 ubuntu-s-1vcpu-512mb-10gb-sfo3-01 empirica[9735]:       _masked: false,
Mar 18 01:47:34 ubuntu-s-1vcpu-512mb-10gb-sfo3-01 empirica[9735]:       _fin: true,
Mar 18 01:47:34 ubuntu-s-1vcpu-512mb-10gb-sfo3-01 empirica[9735]:       _opcode: 8,
Mar 18 01:47:34 ubuntu-s-1vcpu-512mb-10gb-sfo3-01 empirica[9735]:       _totalPayloadLength: 0,
Mar 18 01:47:34 ubuntu-s-1vcpu-512mb-10gb-sfo3-01 empirica[9735]:       _messageLength: 0,
Mar 18 01:47:34 ubuntu-s-1vcpu-512mb-10gb-sfo3-01 empirica[9735]:       _fragments: [],
Mar 18 01:47:34 ubuntu-s-1vcpu-512mb-10gb-sfo3-01 empirica[9735]:       _errored: true,
Mar 18 01:47:34 ubuntu-s-1vcpu-512mb-10gb-sfo3-01 empirica[9735]:       _loop: false,
Mar 18 01:47:34 ubuntu-s-1vcpu-512mb-10gb-sfo3-01 empirica[9735]:       _state: 4,
Mar 18 01:47:34 ubuntu-s-1vcpu-512mb-10gb-sfo3-01 empirica[9735]:       [Symbol(kCapture)]: false,
Mar 18 01:47:34 ubuntu-s-1vcpu-512mb-10gb-sfo3-01 empirica[9735]:       [Symbol(websocket)]: [Circular *1]
Mar 18 01:47:34 ubuntu-s-1vcpu-512mb-10gb-sfo3-01 empirica[9735]:     },
Mar 18 01:47:34 ubuntu-s-1vcpu-512mb-10gb-sfo3-01 empirica[9735]:     _sender: ti {
Mar 18 01:47:34 ubuntu-s-1vcpu-512mb-10gb-sfo3-01 empirica[9735]:       _extensions: [Object],
Mar 18 01:47:34 ubuntu-s-1vcpu-512mb-10gb-sfo3-01 empirica[9735]:       _socket: [Socket],
Mar 18 01:47:34 ubuntu-s-1vcpu-512mb-10gb-sfo3-01 empirica[9735]:       _firstFragment: true,
Mar 18 01:47:34 ubuntu-s-1vcpu-512mb-10gb-sfo3-01 empirica[9735]:       _compress: false,
Mar 18 01:47:34 ubuntu-s-1vcpu-512mb-10gb-sfo3-01 empirica[9735]:       _bufferedBytes: 0,
Mar 18 01:47:34 ubuntu-s-1vcpu-512mb-10gb-sfo3-01 empirica[9735]:       _deflating: false,
Mar 18 01:47:34 ubuntu-s-1vcpu-512mb-10gb-sfo3-01 empirica[9735]:       _queue: []
Mar 18 01:47:34 ubuntu-s-1vcpu-512mb-10gb-sfo3-01 empirica[9735]:     },
Mar 18 01:47:34 ubuntu-s-1vcpu-512mb-10gb-sfo3-01 empirica[9735]:     _socket: Socket {
Mar 18 01:47:34 ubuntu-s-1vcpu-512mb-10gb-sfo3-01 empirica[9735]:       connecting: false,
Mar 18 01:47:34 ubuntu-s-1vcpu-512mb-10gb-sfo3-01 empirica[9735]:       _hadError: false,
Mar 18 01:47:34 ubuntu-s-1vcpu-512mb-10gb-sfo3-01 empirica[9735]:       _parent: null,
Mar 18 01:47:34 ubuntu-s-1vcpu-512mb-10gb-sfo3-01 empirica[9735]:       _host: 'localhost',
Mar 18 01:47:34 ubuntu-s-1vcpu-512mb-10gb-sfo3-01 empirica[9735]:       _closeAfterHandlingError: false,
Mar 18 01:47:34 ubuntu-s-1vcpu-512mb-10gb-sfo3-01 empirica[9735]:       _readableState: [ReadableState],
Mar 18 01:47:34 ubuntu-s-1vcpu-512mb-10gb-sfo3-01 empirica[9735]:       _events: [Object: null prototype],
Mar 18 01:47:34 ubuntu-s-1vcpu-512mb-10gb-sfo3-01 empirica[9735]:       _eventsCount: 2,
Mar 18 01:47:34 ubuntu-s-1vcpu-512mb-10gb-sfo3-01 empirica[9735]:       _maxListeners: undefined,
Mar 18 01:47:34 ubuntu-s-1vcpu-512mb-10gb-sfo3-01 empirica[9735]:       _writableState: [WritableState],
Mar 18 01:47:34 ubuntu-s-1vcpu-512mb-10gb-sfo3-01 empirica[9735]:       allowHalfOpen: false,
Mar 18 01:47:34 ubuntu-s-1vcpu-512mb-10gb-sfo3-01 empirica[9735]:       _sockname: null,
Mar 18 01:47:34 ubuntu-s-1vcpu-512mb-10gb-sfo3-01 empirica[9735]:       _pendingData: null,
Mar 18 01:47:34 ubuntu-s-1vcpu-512mb-10gb-sfo3-01 empirica[9735]:       _pendingEncoding: '',
Mar 18 01:47:34 ubuntu-s-1vcpu-512mb-10gb-sfo3-01 empirica[9735]:       server: null,
Mar 18 01:47:34 ubuntu-s-1vcpu-512mb-10gb-sfo3-01 empirica[9735]:       _server: null,
Mar 18 01:47:34 ubuntu-s-1vcpu-512mb-10gb-sfo3-01 empirica[9735]:       parser: null,
Mar 18 01:47:34 ubuntu-s-1vcpu-512mb-10gb-sfo3-01 empirica[9735]:       _httpMessage: null,
Mar 18 01:47:34 ubuntu-s-1vcpu-512mb-10gb-sfo3-01 empirica[9735]:       autoSelectFamilyAttemptedAddresses: [Array],
Mar 18 01:47:34 ubuntu-s-1vcpu-512mb-10gb-sfo3-01 empirica[9735]:       timeout: 0,
Mar 18 01:47:34 ubuntu-s-1vcpu-512mb-10gb-sfo3-01 empirica[9735]:       write: [Function: writeAfterFIN],
Mar 18 01:47:34 ubuntu-s-1vcpu-512mb-10gb-sfo3-01 empirica[9735]:       [Symbol(async_id_symbol)]: 2906878,
Mar 18 01:47:34 ubuntu-s-1vcpu-512mb-10gb-sfo3-01 empirica[9735]:       [Symbol(kHandle)]: null,
Mar 18 01:47:34 ubuntu-s-1vcpu-512mb-10gb-sfo3-01 empirica[9735]:       [Symbol(lastWriteQueueSize)]: 0,
Mar 18 01:47:34 ubuntu-s-1vcpu-512mb-10gb-sfo3-01 empirica[9735]:       [Symbol(timeout)]: null,
Mar 18 01:47:34 ubuntu-s-1vcpu-512mb-10gb-sfo3-01 empirica[9735]:       [Symbol(kBuffer)]: null,
Mar 18 01:47:34 ubuntu-s-1vcpu-512mb-10gb-sfo3-01 empirica[9735]:       [Symbol(kBufferCb)]: null,
Mar 18 01:47:34 ubuntu-s-1vcpu-512mb-10gb-sfo3-01 empirica[9735]:       [Symbol(kBufferGen)]: null,
Mar 18 01:47:34 ubuntu-s-1vcpu-512mb-10gb-sfo3-01 empirica[9735]:       [Symbol(kCapture)]: false,
Mar 18 01:47:34 ubuntu-s-1vcpu-512mb-10gb-sfo3-01 empirica[9735]:       [Symbol(kSetNoDelay)]: true,
Mar 18 01:47:34 ubuntu-s-1vcpu-512mb-10gb-sfo3-01 empirica[9735]:       [Symbol(kSetKeepAlive)]: false,
Mar 18 01:47:34 ubuntu-s-1vcpu-512mb-10gb-sfo3-01 empirica[9735]:       [Symbol(kSetKeepAliveInitialDelay)]: 0,
Mar 18 01:47:34 ubuntu-s-1vcpu-512mb-10gb-sfo3-01 empirica[9735]:       [Symbol(kBytesRead)]: 8648329,
Mar 18 01:47:34 ubuntu-s-1vcpu-512mb-10gb-sfo3-01 empirica[9735]:       [Symbol(kBytesWritten)]: 104766,
Mar 18 01:47:34 ubuntu-s-1vcpu-512mb-10gb-sfo3-01 empirica[9735]:       [Symbol(websocket)]: undefined
Mar 18 01:47:34 ubuntu-s-1vcpu-512mb-10gb-sfo3-01 empirica[9735]:     },
Mar 18 01:47:34 ubuntu-s-1vcpu-512mb-10gb-sfo3-01 empirica[9735]:     _bufferedAmount: 0,
Mar 18 01:47:34 ubuntu-s-1vcpu-512mb-10gb-sfo3-01 empirica[9735]:     _isServer: false,
Mar 18 01:47:34 ubuntu-s-1vcpu-512mb-10gb-sfo3-01 empirica[9735]:     _redirects: 0,
Mar 18 01:47:34 ubuntu-s-1vcpu-512mb-10gb-sfo3-01 empirica[9735]:     _autoPong: true,
Mar 18 01:47:34 ubuntu-s-1vcpu-512mb-10gb-sfo3-01 empirica[9735]:     _url: 'ws://localhost:3000/query',
Mar 18 01:47:34 ubuntu-s-1vcpu-512mb-10gb-sfo3-01 empirica[9735]:     _req: null,
Mar 18 01:47:34 ubuntu-s-1vcpu-512mb-10gb-sfo3-01 empirica[9735]:     [Symbol(kCapture)]: false
Mar 18 01:47:34 ubuntu-s-1vcpu-512mb-10gb-sfo3-01 empirica[9735]:   },
Mar 18 01:47:34 ubuntu-s-1vcpu-512mb-10gb-sfo3-01 empirica[9735]:   [Symbol(kType)]: 'error',
Mar 18 01:47:34 ubuntu-s-1vcpu-512mb-10gb-sfo3-01 empirica[9735]:   [Symbol(kError)]: RangeError: Invalid WebSocket frame: invalid status code 1006
Mar 18 01:47:34 ubuntu-s-1vcpu-512mb-10gb-sfo3-01 empirica[9735]:       at a2.controlMessage (/tmp/65ff50ec463f583b/node_modules/ws/lib/receiver.js:633:30)
Mar 18 01:47:34 ubuntu-s-1vcpu-512mb-10gb-sfo3-01 empirica[9735]:       at a2.getData (/tmp/65ff50ec463f583b/node_modules/ws/lib/receiver.js:481:12)
Mar 18 01:47:34 ubuntu-s-1vcpu-512mb-10gb-sfo3-01 empirica[9735]:       at a2.startLoop (/tmp/65ff50ec463f583b/node_modules/ws/lib/receiver.js:171:16)
Mar 18 01:47:34 ubuntu-s-1vcpu-512mb-10gb-sfo3-01 empirica[9735]:       at <anonymous> (/tmp/65ff50ec463f583b/node_modules/ws/lib/receiver.js:535:42)
Mar 18 01:47:34 ubuntu-s-1vcpu-512mb-10gb-sfo3-01 empirica[9735]:       at <anonymous> (/tmp/65ff50ec463f583b/node_modules/ws/lib/permessage-deflate.js:309:9)
Mar 18 01:47:34 ubuntu-s-1vcpu-512mb-10gb-sfo3-01 empirica[9735]:       at <anonymous> (/tmp/65ff50ec463f583b/node_modules/ws/lib/permessage-deflate.js:392:7)
Mar 18 01:47:34 ubuntu-s-1vcpu-512mb-10gb-sfo3-01 empirica[9735]:       at afterWrite (node:internal/streams/writable:693:5)
Mar 18 01:47:34 ubuntu-s-1vcpu-512mb-10gb-sfo3-01 empirica[9735]:       at onwrite (node:internal/streams/writable:671:7)
Mar 18 01:47:34 ubuntu-s-1vcpu-512mb-10gb-sfo3-01 empirica[9735]:       at Zlib.cb (node:internal/streams/transform:195:7)
Mar 18 01:47:34 ubuntu-s-1vcpu-512mb-10gb-sfo3-01 empirica[9735]:       at Zlib.processCallback (node:zlib:613:8) {
Mar 18 01:47:34 ubuntu-s-1vcpu-512mb-10gb-sfo3-01 empirica[9735]:     code: 'WS_ERR_INVALID_CLOSE_CODE',
Mar 18 01:47:34 ubuntu-s-1vcpu-512mb-10gb-sfo3-01 empirica[9735]:     [Symbol(status-code)]: 1002
Mar 18 01:47:34 ubuntu-s-1vcpu-512mb-10gb-sfo3-01 empirica[9735]:   },
Mar 18 01:47:34 ubuntu-s-1vcpu-512mb-10gb-sfo3-01 empirica[9735]:   [Symbol(kMessage)]: 'Invalid WebSocket frame: invalid status code 1006'
Mar 18 01:47:34 ubuntu-s-1vcpu-512mb-10gb-sfo3-01 empirica[9735]: }
```
