### ISSUE TITLE
fatal error: concurrent map writes

### ISSUE THREAD

**Issue by Isaiah-zzz** [empiricaly/empirica#582]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

I ran the experiment and encountered a` fatal error: concurrent map writes`. After restarting, the experiment got `failed load: [GraphQL] transition step: invalid transition: from state mismatch with previous state`. Participants who were halfway through seem to be able to finish, but new participants are unable to load in.

### Steps To Reproduce

running [this experiment](https://github.com/SocialInteractionLab/Candor)

### Empirica Version

```text
Version: v1.11.6
SHA:     69b40d9
Build:   224
Branch:  main
Time:    2024-09-29T07:27:52Z
```

### What OS are you seeing the problem on?

Linux

### Relevant log output

```shell
fatal error: concurrent map writes

goroutine 50156 [running]:
github.com/empiricaly/tajriba/internal/runtime.(*changesSub).publish(0xc00245d900, {0xc00039be90?, 0xc002e735e0?}, {0xc000c00400, 0x5d, 0x80})
	/go/pkg/mod/github.com/empiricaly/tajriba@v1.7.1/internal/runtime/change.go:77 +0x1b5
github.com/empiricaly/tajriba/internal/runtime.(*Runtime).pushLinks(0xc0000a0cc0, {0xeb1490, 0xc0010b4db0}, {0xc0053cdc00, 0x9, 0x10?}, 0xc00245d900)
	/go/pkg/mod/github.com/empiricaly/tajriba@v1.7.1/internal/runtime/change.go:333 +0x8f2
github.com/empiricaly/tajriba/internal/runtime.(*Runtime).SubChanges(0xc0000a0cc0, {0xeb1490, 0xc0010b4db0})
	/go/pkg/mod/github.com/empiricaly/tajriba@v1.7.1/internal/runtime/change.go:373 +0x30a
github.com/empiricaly/tajriba/internal/graph.(*subscriptionResolver).Changes(0xc00061c2a0?, {0xeb1490, 0xc0010b4db0})
	/go/pkg/mod/github.com/empiricaly/tajriba@v1.7.1/internal/graph/change.resolvers.go:19 +0x50
github.com/empiricaly/tajriba/internal/graph.(*executionContext)._Subscription_changes.func2.1({0xeb1490?, 0xc0010b4db0})
	/go/pkg/mod/github.com/empiricaly/tajriba@v1.7.1/internal/graph/generated.go:9905 +0x75
github.com/empiricaly/tajriba.Setup.NewSchema.func1({0xeb1490, 0xc0010b4db0}, {0xc0010b4db0?, 0xc536e0?}, 0xc0037e4348, {0xd7d1f8, 0xb})
	/go/pkg/mod/github.com/empiricaly/tajriba@v1.7.1/internal/graph/resolver.go:58 +0x109
github.com/empiricaly/tajriba/internal/graph.(*executionContext)._Subscription_changes.func2.2({0xeb1490, 0xc0010b4db0})
	/go/pkg/mod/github.com/empiricaly/tajriba@v1.7.1/internal/graph/generated.go:9915 +0x84
github.com/empiricaly/tajriba/internal/graph.(*executionContext)._Subscription_changes.func2({0xeb1490, 0xc0010b4db0})
	/go/pkg/mod/github.com/empiricaly/tajriba@v1.7.1/internal/graph/generated.go:9918 +0xb2
github.com/99designs/gqlgen/graphql/executor.processExtensions.func4({0xeb1490?, 0xc0010b4db0?}, 0xc001d2c930?)
	/go/pkg/mod/github.com/99designs/gqlgen@v0.17.36/graphql/executor/extensions.go:72 +0x22
github.com/empiricaly/tajriba/internal/graph.(*executionContext)._Subscription_changes(0xc001154ea0, {0xeb1490, 0xc0010b4d80}, {0xc00263a6c0, {0xc0010b4d50, 0x3, 0x3}, 0x0})
	/go/pkg/mod/github.com/empiricaly/tajriba@v1.7.1/internal/graph/generated.go:9902 +0x2a3
github.com/empiricaly/tajriba/internal/graph.(*executionContext)._Subscription(0xc001154ea0, {0xeb1490, 0xc0010b4cc0}, {0xc0026991f0, 0x1, 0x1})
	/go/pkg/mod/github.com/empiricaly/tajriba@v1.7.1/internal/graph/generated.go:15960 +0x227
github.com/empiricaly/tajriba/internal/graph.(*executableSchema).Exec(0xc0000d8000, {0xeb1490, 0xc0010b4cc0})
	/go/pkg/mod/github.com/empiricaly/tajriba@v1.7.1/internal/graph/generated.go:1743 +0x8c5
github.com/99designs/gqlgen/graphql/executor.(*Executor).DispatchOperation.func1({0xeb1490?, 0xc0010b4c90})
	/go/pkg/mod/github.com/99designs/gqlgen@v0.17.36/graphql/executor/executor.go:111 +0x10b
github.com/99designs/gqlgen/graphql/executor.processExtensions.func1({0xeb1490?, 0xc0010b4c90?}, 0xc547a0?)
	/go/pkg/mod/github.com/99designs/gqlgen@v0.17.36/graphql/executor/extensions.go:63 +0x22
github.com/99designs/gqlgen/graphql/executor.(*Executor).DispatchOperation(0xc0001d66e0, {0xeb1490?, 0xc0010b4c30?}, 0x14daf80?)
	/go/pkg/mod/github.com/99designs/gqlgen@v0.17.36/graphql/executor/executor.go:107 +0xc3
github.com/99designs/gqlgen/graphql/handler/transport.(*wsConnection).subscribe.func1()
	/go/pkg/mod/github.com/99designs/gqlgen@v0.17.36/graphql/handler/transport/websocket.go:381 +0x164
created by github.com/99designs/gqlgen/graphql/handler/transport.(*wsConnection).subscribe in goroutine 50103
	/go/pkg/mod/github.com/99designs/gqlgen@v0.17.36/graphql/handler/transport/websocket.go:356 +0x58a

goroutine 1 [semacquire, 76 minutes]:
sync.runtime_Semacquire(0x802ce5?)
	/usr/local/go/src/runtime/sema.go:62 +0x25
sync.(*WaitGroup).Wait(0x14efa80?)
	/usr/local/go/src/sync/waitgroup.go:116 +0x48
github.com/empiricaly/empirica/internal/server.(*Server).Wait(...)
	/build/internal/server/server.go:143
github.com/empiricaly/empirica/internal/bundle.Serve({0xeb14c8?, 0xc00054fcc0}, 0x3?, {0x7ffce16e4e81?, 0x4?}, 0x58?, 0xc2?)
	/build/internal/bundle/serve.go:194 +0xa8d
github.com/empiricaly/empirica/cmds/empirica/cmd.addServeCommand.func1(0xc0000f4400?, {0xc00053cf40, 0x4?, 0xd72271?})
	/build/cmds/empirica/cmd/serve.go:54 +0x232
github.com/spf13/cobra.(*Command).execute(0xc000497b80, {0xc00053cf20, 0x2, 0x2})
	/go/pkg/mod/github.com/spf13/cobra@v1.5.0/command.go:872 +0x6aa
github.com/spf13/cobra.(*Command).ExecuteC(0xc000497400)
	/go/pkg/mod/github.com/spf13/cobra@v1.5.0/command.go:990 +0x38d
github.com/spf13/cobra.(*Command).Execute(...)
	/go/pkg/mod/github.com/spf13/cobra@v1.5.0/command.go:918
github.com/empiricaly/empirica/cmds/empirica/cmd.Execute()
	/build/cmds/empirica/cmd/root.go:144 +0x236
main.main()
	/build/cmds/empirica/main.go:10 +0xf

goroutine 6 [chan receive, 76 minutes]:
github.com/rjeczalik/notify.(*nonrecursiveTree).dispatch(0xc0000a08a0, 0x0?)
	/go/pkg/mod/github.com/rjeczalik/notify@v0.0.0-20181126183243-629144ba06a1/tree_nonrecursive.go:36 +0x45
created by github.com/rjeczalik/notify.newNonrecursiveTree in goroutine 1
	/go/pkg/mod/github.com/rjeczalik/notify@v0.0.0-20181126183243-629144ba06a1/tree_nonrecursive.go:29 +0x145

goroutine 7 [chan receive, 76 minutes]:
github.com/rjeczalik/notify.(*nonrecursiveTree).internal(0xc0000a08a0, 0xc0000a0840)
	/go/pkg/mod/github.com/rjeczalik/notify@v0.0.0-20181126183243-629144ba06a1/tree_nonrecursive.go:81 +0x47
created by github.com/rjeczalik/notify.newNonrecursiveTree in goroutine 1
	/go/pkg/mod/github.com/rjeczalik/notify@v0.0.0-20181126183243-629144ba06a1/tree_nonrecursive.go:30 +0x193

goroutine 11 [chan receive, 76 minutes]:
github.com/empiricaly/empirica/cmds/empirica/cmd.initContext.func1()
	/build/cmds/empirica/cmd/root.go:204 +0xd1
created by github.com/empiricaly/empirica/cmds/empirica/cmd.initContext in goroutine 1
	/build/cmds/empirica/cmd/root.go:201 +0x76

goroutine 50 [syscall, 76 minutes]:
os/signal.signal_recv()
	/usr/local/go/src/runtime/sigqueue.go:152 +0x29
os/signal.loop()
	/usr/local/go/src/os/signal/signal_unix.go:23 +0x13
created by os/signal.Notify.func1.1 in goroutine 11
	/usr/local/go/src/os/signal/signal.go:151 +0x1f

goroutine 12 [syscall, 76 minutes]:
syscall.Syscall6(0xc0001802c0?, 0xc00001c060?, 0xc00008bd46?, 0xc00008be68?, 0x71b2e4?, 0xc00019e030?, 0x0?)
	/usr/local/go/src/syscall/syscall_linux.go:91 +0x30
os.(*Process).blockUntilWaitable(0xc00045c0c0)
	/usr/local/go/src/os/wait_waitid.go:32 +0x76
os.(*Process).wait(0xc00045c0c0)
	/usr/local/go/src/os/exec_unix.go:22 +0x25
os.(*Process).Wait(...)
	/usr/local/go/src/os/exec.go:134
os/exec.(*Cmd).Wait(0xc0001802c0)
	/usr/local/go/src/os/exec/exec.go:890 +0x45
github.com/empiricaly/empirica/internal/bundle.Serve.func1({0xeb14c8, 0xc00054fcc0})
	/build/internal/bundle/serve.go:141 +0x6e5
created by github.com/empiricaly/empirica/internal/bundle.Serve in goroutine 1
	/build/internal/bundle/serve.go:85 +0x325

goroutine 51 [select, 76 minutes]:
os/exec.(*Cmd).watchCtx(0xc0001802c0, 0xc0005621e0)
	/usr/local/go/src/os/exec/exec.go:757 +0xb5
created by os/exec.(*Cmd).Start in goroutine 12
	/usr/local/go/src/os/exec/exec.go:743 +0x9c9

goroutine 13 [select]:
github.com/empiricaly/tajriba/internal/store.(*Conn).flusher(0xc0000a0c00)
	/go/pkg/mod/github.com/empiricaly/tajriba@v1.7.1/internal/store/store.go:201 +0x69
created by github.com/empiricaly/tajriba/internal/store.Connect in goroutine 1
	/go/pkg/mod/github.com/empiricaly/tajriba@v1.7.1/internal/store/store.go:48 +0xf6

goroutine 42 [chan receive, 76 minutes]:
github.com/empiricaly/tajriba/internal/runtime.NewOnEventSub.func1()
	/go/pkg/mod/github.com/empiricaly/tajriba@v1.7.1/internal/runtime/hooks.go:65 +0x2c
created by github.com/empiricaly/tajriba/internal/runtime.NewOnEventSub in goroutine 39
	/go/pkg/mod/github.com/empiricaly/tajriba@v1.7.1/internal/runtime/hooks.go:64 +0x105

goroutine 41 [sync.Cond.Wait]:
sync.runtime_notifyListWait(0xc0004fdfd0, 0x2a)
	/usr/local/go/src/runtime/sema.go:527 +0x159
sync.(*Cond).Wait(0xc000114768?)
	/usr/local/go/src/sync/cond.go:70 +0x85
github.com/empiricaly/tajriba/internal/runtime.(*SendBuffer[...]).process(0xeb4f80)
	/go/pkg/mod/github.com/empiricaly/tajriba@v1.7.1/internal/runtime/sendbuffer.go:67 +0x12b
created by github.com/empiricaly/tajriba/internal/runtime.NewSendBuffer[...] in goroutine 39
	/go/pkg/mod/github.com/empiricaly/tajriba@v1.7.1/internal/runtime/sendbuffer.go:31 +0x137
... see log file
```

### Anything else?

[Kr2l.log](https://github.com/user-attachments/files/17390297/Kr2l.log)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by npaton** [comment]
This should be fixed in the new release (v1.12.0). Let me know if anything similar occurs after the upgrade. 🙏
