### ISSUE TITLE
Failed Lobbies and Terminate Batch Not Ending Games

### ISSUE THREAD

**Issue by JMankewitz** [empiricaly/empirica#590]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

When any game with the "shared / fail" configuration or if a batch is terminated with the "stop" button in the admin panel, the games kick any currently assigned players with the "game failed" or "game terminated" exitReason. However, the games are not actually set to "ended". Empirica continuously attempts to assign new joining participants to these games (even if actual open games are available). These participants are stuck in a loading screen and the server reports this error:

```
[server] 19:41:38.946 ERR Error caught in "player" callback:
[server] 19:41:39.001 ERR Error: cannot assign player to ended Game
[server] 19:41:39.001 ERR   at Qv.assignPlayer (/Users/mankewitz/Projects/empirica-demos/empirica-demo/demo-expt/server/node_modules/@empirica/core/src/admin/classic/models.ts:185:13)
[server] 19:41:39.001 ERR   at u (/Users/mankewitz/Projects/empirica-demos/empirica-demo/demo-expt/server/node_modules/@empirica/core/src/admin/classic/classic.ts:190:20)
[server] 19:41:39.001 ERR   at Object.callback (/Users/mankewitz/Projects/empirica-demos/empirica-demo/demo-expt/server/node_modules/@empirica/core/src/admin/classic/classic.ts:321:15)
[server] 19:41:39.001 ERR   at <anonymous> (/Users/mankewitz/Projects/empirica-demos/empirica-demo/demo-expt/server/node_modules/@empirica/core/src/admin/cake.ts:232:30)
[server] 19:41:39.001 ERR   at Object.next (/Users/mankewitz/Projects/empirica-demos/empirica-demo/demo-expt/server/node_modules/@empirica/core/src/admin/observables.ts:78:17)
[server] 19:41:39.001 ERR   at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

This made more obvious with the output of the `games.csv`. The games that should have closed due to the failed lobby have a `endedReason` value of `shared lobby timeout` and `status` is `failed`, but `ended` is still `FALSE`. 

### Steps To Reproduce

1. Setup skepeton experiment

```
empirica create demo-experiment
cd empirica
empirica
```

2. Create a lobby config with a shorter timeout for testing:

```
    - name: Short shared fail
      kind: shared
      duration: 1m0s
      strategy: fail
```

3. Create batch with a 2-player game
4. Create 3+ test participants
5. Have participants sit in lobby for +1m
6. Observe those participants are sent to the exit steps
7. Create an additional test participant, see they sit in the loading screen.

### Empirica Version

```text
Version: v1.12.0
SHA:     152f8e3
Build:   228
Branch:  main
Time:    2024-10-20T06:04:46Z

Client:  1.12.0
Server:  1.12.0
```

### What OS are you seeing the problem on?

macOS

### What browser are you seeing the problem on?

Firefox, Chrome

### Relevant log output

```shell
[server] 19:41:38.946 ERR Error caught in "player" callback:
[server] 19:41:39.001 ERR Error: cannot assign player to ended Game
[server] 19:41:39.001 ERR   at Qv.assignPlayer (/Users/mankewitz/Projects/empirica-demos/empirica-demo/demo-expt/server/node_modules/@empirica/core/src/admin/classic/models.ts:185:13)
[server] 19:41:39.001 ERR   at u (/Users/mankewitz/Projects/empirica-demos/empirica-demo/demo-expt/server/node_modules/@empirica/core/src/admin/classic/classic.ts:190:20)
[server] 19:41:39.001 ERR   at Object.callback (/Users/mankewitz/Projects/empirica-demos/empirica-demo/demo-expt/server/node_modules/@empirica/core/src/admin/classic/classic.ts:321:15)
[server] 19:41:39.001 ERR   at <anonymous> (/Users/mankewitz/Projects/empirica-demos/empirica-demo/demo-expt/server/node_modules/@empirica/core/src/admin/cake.ts:232:30)
[server] 19:41:39.001 ERR   at Object.next (/Users/mankewitz/Projects/empirica-demos/empirica-demo/demo-expt/server/node_modules/@empirica/core/src/admin/observables.ts:78:17)
[server] 19:41:39.001 ERR   at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

### Anything else?

h/t to @malsobay for helping track down these pieces! Here is the [game.csv](https://github.com/user-attachments/files/18235113/game.csv) from a demo run. 

I suspect the issue is happening because hasEnded() checks the game status: https://github.com/empiricaly/empirica/blob/152f8e39a1daa95e1ad6599ee1ecf482d68d9fad/lib/%40empirica/core/src/player/classic/classic.ts#L13 

And the available games include any that are just not started (vs ones that have an ended status...) https://github.com/empiricaly/empirica/blob/152f8e39a1daa95e1ad6599ee1ecf482d68d9fad/lib/%40empirica/core/src/admin/classic/classic.ts#L126

I also think there's trickiness around game ending code because the Game.end() method doesn't actually change the "ended" value (only "status" and "endedReason") https://github.com/empiricaly/empirica/blob/152f8e39a1daa95e1ad6599ee1ecf482d68d9fad/lib/%40empirica/core/src/admin/classic/models.ts#L612

Happy to do more testing if that's easiest!

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by npaton** [comment]
Should be fixed in the latest release. Please reopen if you have any issues. 🙏
