### ISSUE TITLE
TCP/Promise/Mongo error?

### ISSUE THREAD

**Issue by joshua-a-becker** [empiricaly/empirica#69]
I have noticed this error a few times, despite the app apparently functioning properly

this particular error is while running with the default local MongoDB but I believe i've also seen it when using a remote mLab mongodb. 

it doesn't seem to cause any problems but i thought i should report it.

```
.browser+web.browser.legacy+web.cordova/npm/node_modules/mongodb-core/lib/connection/connection.js:452:17)
I20180822-21:26:29.455(0)?     at emitOne (events.js:116:13)
I20180822-21:26:29.456(0)?     at Socket.emit (events.js:211:7)
I20180822-21:26:29.456(0)?     at addChunk (_stream_readable.js:263:12)
I20180822-21:26:29.456(0)?     at readableAddChunk (_stream_readable.js:250:11)
I20180822-21:26:29.457(0)?     at Socket.Readable.push (_stream_readable.js:208:10)
I20180822-21:26:29.457(0)?     at TCP.onread (net.js:597:20)
I20180822-21:26:29.457(0)?  => awaited here:
I20180822-21:26:29.458(0)?     at Function.Promise.await (/home/joshua/.meteor/packages/promise/.0.11.1.ihl06c.0g81b++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/meteor-promise/promise_server.js:56:12)
I20180822-21:26:29.466(0)?     at Promise.asyncApply (packages/mongo/mongo_driver.js:1034:11)
I20180822-21:26:29.466(0)?     at /home/joshua/.meteor/packages/promise/.0.11.1.ihl06c.0g81b++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/meteor-promise/fiber_pool.js:43:40
I20180822-21:26:29.467(0)?  => awaited here:
I20180822-21:26:29.467(0)?     at Promise.await (/home/joshua/.meteor/packages/promise/.0.11.1.ihl06c.0g81b++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/meteor-promise/promise_server.js:60:12)
I20180822-21:26:29.467(0)?     at SynchronousCursor._nextObject (packages/mongo/mongo_driver.js:1083:12)
I20180822-21:26:29.467(0)?     at SynchronousCursor.forEach (packages/mongo/mongo_driver.js:1097:22)
I20180822-21:26:29.467(0)?     at Cursor.(anonymous function) [as forEach] (packages/mongo/mongo_driver.js:879:44)
I20180822-21:26:29.467(0)?     at Object.task (imports/core/api/game-lobbies/server/cron.js:92:29)
I20180822-21:26:29.468(0)?     at run (imports/core/startup/server/cron.js:53:14)
I20180822-21:26:29.468(0)?     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1189:12)
I20180822-21:26:29.468(0)?     at packages/meteor.js:505:25
I20180822-21:26:29.468(0)?     at runWithEnvironment (packages/meteor.js:1241:24)
I20180822-21:26:29.468(0)?   name: 'MongoError',
I20180822-21:26:29.469(0)?   message: 'cursor id 105937251601 not found',
I20180822-21:26:29.469(0)?   ok: 0,
I20180822-21:26:29.469(0)?   errmsg: 'cursor id 105937251601 not found',
I20180822-21:26:29.469(0)?   code: 43,
I20180822-21:26:29.469(0)?   codeName: 'CursorNotFound',
I20180822-21:26:29.469(0)?   operationTime: Timestamp { _bsontype: 'Timestamp', low_: 2, high_: 1534973176 },
I20180822-21:26:29.470(0)?   '$clusterTime':
I20180822-21:26:29.470(0)?    { clusterTime: Timestamp { _bsontype: 'Timestamp', low_: 2, high_: 1534973176 },
I20180822-21:26:29.470(0)?      signature: { hash: [Object], keyId: 0 } } }

```

**Comment by amaatouq** [comment]
Probably related to #68 

In the meantime, you can add the indices manually.

**Comment by amaatouq** [comment]
ok, this should be fixed now. I'll close the issue--if still appears after the latest release, please reopen.
