### ISSUE TITLE
When consent is null, playerIdParam is not pulled from URL

### ISSUE THREAD

**Issue by joshua-a-becker** [empiricaly/empirica#75]
This is an issue if consent is completed elsewhere (e.g., in the MTurk hit or on a routing page)

Solution:  in `NewPlayer.jsx`, move the `if (playerIdParam) {...} `block *out of* `handleConsent()` and *into* the main `render() `function just below the `if (!consented && ConsentComponent)` logic  (this location ensures that consent is always handled, if necessary, before preceding with autologin)

**Comment by joshua-a-becker** [comment]
Sorry, I'm still a bit of a n00b with github and I guess I didn't fork properly---this can be pulled from
https://github.com/joshua-a-becker/binary-woc/blob/master/imports/core/ui/components/NewPlayer.jsx

**Comment by npaton** [comment]
Thank Joshua. See PR #76 I created to fix this, let me know if that works for you.

**Comment by joshua-a-becker** [comment]
This version works OK, but throws an error when consent is null (i.e., skipped).  I'll circle back around to see if I can figure out what's causing it, but not today:

```
I20180926-18:55:00.320(0)? Exception while invoking method 'Players.methods.updateData' { MongoError: Updating the path 'data' would create a conflict at 'data'
I20180926-18:55:00.321(0)?     at Function.MongoError.create (/home/jab2157/.meteor/packages/npm-mongo/.3.0.7.1qmskwk.aq1q++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/mongodb-core/lib/error.js:45:10)
I20180926-18:55:00.321(0)?     at toError (/home/jab2157/.meteor/packages/npm-mongo/.3.0.7.1qmskwk.aq1q++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/mongodb/lib/utils.js:149:22)
I20180926-18:55:00.321(0)?     at /home/jab2157/.meteor/packages/npm-mongo/.3.0.7.1qmskwk.aq1q++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/mongodb/lib/collection.js:1029:39
I20180926-18:55:00.321(0)?     at handler (/home/jab2157/.meteor/packages/npm-mongo/.3.0.7.1qmskwk.aq1q++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/mongodb-core/lib/topologies/replset.js:1209:22)
I20180926-18:55:00.321(0)?     at /home/jab2157/.meteor/packages/npm-mongo/.3.0.7.1qmskwk.aq1q++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/mongodb-core/lib/connection/pool.js:544:18
I20180926-18:55:00.322(0)?     at _combinedTickCallback (internal/process/next_tick.js:131:7)
I20180926-18:55:00.322(0)?     at process._tickDomainCallback (internal/process/next_tick.js:218:9)
I20180926-18:55:00.322(0)?   name: 'MongoError',
I20180926-18:55:00.322(0)?   message: 'Updating the path \'data\' would create a conflict at \'data\'',
I20180926-18:55:00.322(0)?   driver: true,
I20180926-18:55:00.322(0)?   index: 0,
I20180926-18:55:00.322(0)?   code: 40,
I20180926-18:55:00.322(0)?   errmsg: 'Updating the path \'data\' would create a conflict at \'data\'' }

```

**Comment by npaton** [comment]
This error does not seem to be related to the consent changes. `Players.methods.updateData` not called in `NewPlayer.jsx`. Let me know how it goes.

**Comment by joshua-a-becker** [comment]
Yes, this error was unrelated.  This update works great.

**Comment by joshua-a-becker** [comment]
For anyone who chances across this error: it was due to me trying to player.set("value","") to an empty value because I was rushing through the intake form.
